unpackaged/post/02_heda_objects_ui/objects/hed__Trigger_Handler__c.object
<CustomObject>
    <description>Stores which classes to run in response to DML performed on an object.</description>
    <fields>
        <fullName>hed__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates that this module is active</description>
        <inlineHelpText>Indicates that this module is active</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>hed__Class__c</fullName>
        <description>Name of the class to be run</description>
        <inlineHelpText>Name of the class to be run</inlineHelpText>
        <label>Class</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>hed__Load_Order__c</fullName>
        <description>Order in which this module should be run, helps maintain dependencies in the modules and data.</description>
        <inlineHelpText>Order in which this module should be run, helps maintain dependencies in the modules and data.</inlineHelpText>
        <label>Load Order</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>hed__Object__c</fullName>
        <description>Name of the object this handler should be run for</description>
        <inlineHelpText>Name of the object this handler should be run for</inlineHelpText>
        <label>Object</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>hed__Trigger_Action__c</fullName>
        <description>Trigger Action in which this module should fire</description>
        <inlineHelpText>Trigger Action in which this module should fire</inlineHelpText>
        <label>Trigger Action</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BeforeInsert</fullName>
                </value>
                <value>
                    <fullName>BeforeUpdate</fullName>
                </value>
                <value>
                    <fullName>BeforeDelete</fullName>
                </value>
                <value>
                    <fullName>AfterInsert</fullName>
                </value>
                <value>
                    <fullName>AfterUpdate</fullName>
                </value>
                <value>
                    <fullName>AfterDelete</fullName>
                </value>
                <value>
                    <fullName>AfterUndelete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>hed__User_Managed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The record is managed by the user and updates won&apos;t be pushed to it.</description>
        <inlineHelpText>Check it if you intent to manage the record yourself. Be aware that updates to the package won&apos;t update the record.</inlineHelpText>
        <label>User Managed</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger Handler</label>
    <nameField>
        <label>Trigger Handler Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trigger Handlers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/ready/LoginAndRegister/classes/redu_USR_AssignCommunityPermSet_TDTM.cls
/**
 * @author          WDCi(LKoh)
 * @date            Dec 2021
 * @group           User
 * @description     Trigger to assign community student with perm set
 * 
 */

global without sharing class redu_USR_AssignCommunityPermSet_TDTM extends hed.TDTM_Runnable {
    
    public static Set<Id> processedIds = new Set<Id>();

    /**
     * @description Trigger Handler on Contact that handle contact management.
     * @param newList the list of Contact from trigger new
     * @param oldList the list of Contact from trigger old
     * @param triggerAction which trigger event (BeforeInsert, AfterInsert, etc.).
     * @param objResult the describe for Contact
     * @return DmlWrapper
     */
    public override DmlWrapper run(List<SObject> newList, 
                                   List<SObject> oldList, 
                                   hed.TDTM_Runnable.Action triggerAction, 
                                   Schema.DescribeSObjectResult objResult) {

        hed.TDTM_Runnable.DmlWrapper dmlWrapper = null;

        if(triggerAction == hed.TDTM_Runnable.Action.AfterInsert){
            List<User> newUserList = (List<User>) newList;
            List<PermissionSetGroup> studPermSetGroups = redu_LoginRegister_UTIL.getStudentPermissionSetGroup();
            Profile studentProfile = redu_LoginRegister_UTIL.getStudentProfile();

            Set<Id> userIds = new Set<Id>();
            if(!studPermSetGroups.isEmpty() && studentProfile != null){
                for(User newUsr : newUserList){
                    if(!processedIds.contains(newUsr.Id) && newUsr.ContactId != null && newUsr.ProfileId == studentProfile.Id){
                        userIds.add(newUsr.Id);
                        processedIds.add(newUsr.Id);
                    }
                }
            }
            
            assignPermissionSetGroup(userIds);
        }
        
        return dmlWrapper;
    }
     
    @future
    public static void assignPermissionSetGroup(Set<Id> userIds){

        List<PermissionSetAssignment> newPermSetAssignments = new List<PermissionSetAssignment>();
        List<PermissionSetGroup> studPermSetGroup = redu_LoginRegister_UTIL.getStudentPermissionSetGroup();
        
        for(Id usrId : userIds){
            for(PermissionSetGroup psg : studPermSetGroup){
                PermissionSetAssignment psa = new PermissionSetAssignment(AssigneeId = usrId, PermissionSetGroupId = psg.Id);

                newPermSetAssignments.add(psa);
            }
        }

        insert newPermSetAssignments;        
    }

    //────────────────────────────────────────────────────┐
    // TDTM Setting Installer
    //────────────────────────────────────────────────────┘
    public static void installTDTMSetting() {
        List<hed__Trigger_Handler__c> currentTriggerHandlerList = 
            [SELECT Id, hed__Active__c, rio_ed__Unique_Key__c, hed__Object__c, hed__Load_Order__c, hed__Trigger_Action__c, hed__Class__c
                FROM hed__Trigger_Handler__c 
                WHERE hed__Active__c = true AND rio_ed__Unique_Key__c = 'User_redu_USR_AssignCommunityPermSet_TDTM_3'];
        if (currentTriggerHandlerList.isEmpty()) {
            hed__Trigger_Handler__c newTriggerHandler = new hed__Trigger_Handler__c(
                Name = 'RIOREADY_AssignCommunityPermSet',
                hed__Object__c = 'User',
                hed__Load_Order__c = 3,
                hed__Trigger_Action__c = 'AfterInsert',
                hed__Class__c = 'redu_USR_AssignCommunityPermSet_TDTM',
                hed__Active__c = true,
                hed__User_Managed__c = true,
                rio_ed__Unique_Key__c = 'User_redu_USR_AssignCommunityPermSet_TDTM_3'
            );
            insert newTriggerHandler;
        }
    }
}