unpackaged/post/02_heda_objects_ui/objects/hed__Trigger_Handler__c.object
<CustomObject>
    <description>Stores which classes to run in response to DML performed on an object.</description>
    <fields>
        <fullName>hed__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates that this module is active</description>
        <inlineHelpText>Indicates that this module is active</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>hed__Class__c</fullName>
        <description>Name of the class to be run</description>
        <inlineHelpText>Name of the class to be run</inlineHelpText>
        <label>Class</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>hed__Load_Order__c</fullName>
        <description>Order in which this module should be run, helps maintain dependencies in the modules and data.</description>
        <inlineHelpText>Order in which this module should be run, helps maintain dependencies in the modules and data.</inlineHelpText>
        <label>Load Order</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>hed__Object__c</fullName>
        <description>Name of the object this handler should be run for</description>
        <inlineHelpText>Name of the object this handler should be run for</inlineHelpText>
        <label>Object</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>hed__Trigger_Action__c</fullName>
        <description>Trigger Action in which this module should fire</description>
        <inlineHelpText>Trigger Action in which this module should fire</inlineHelpText>
        <label>Trigger Action</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BeforeInsert</fullName>
                </value>
                <value>
                    <fullName>BeforeUpdate</fullName>
                </value>
                <value>
                    <fullName>BeforeDelete</fullName>
                </value>
                <value>
                    <fullName>AfterInsert</fullName>
                </value>
                <value>
                    <fullName>AfterUpdate</fullName>
                </value>
                <value>
                    <fullName>AfterDelete</fullName>
                </value>
                <value>
                    <fullName>AfterUndelete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>hed__User_Managed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The record is managed by the user and updates won&apos;t be pushed to it.</description>
        <inlineHelpText>Check it if you intent to manage the record yourself. Be aware that updates to the package won&apos;t update the record.</inlineHelpText>
        <label>User Managed</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger Handler</label>
    <nameField>
        <label>Trigger Handler Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trigger Handlers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/config/ready/19_Student_Ledger/objects/redu_Ledger_Entry__c.object
<CustomObject>
    <fields>
        <fullName>redu_Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>redu_Payment_Amount__c</fullName>
        <label>Payment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>redu_Related_Payment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Payment</label>
        <referenceTo>rio_ed__Fee_Payment__c</referenceTo>
        <relationshipLabel>Ledger Entries</relationshipLabel>
        <relationshipName>Ledger_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>redu_Student_Ledger__c</fullName>
        <label>Student Ledger</label>
        <referenceTo>redu_Student_Ledger__c</referenceTo>
        <relationshipLabel>Ledger Entries</relationshipLabel>
        <relationshipName>Ledger_Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>redu_Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Fee</fullName>
                </value>
                <value>
                    <fullName>Payment</fullName>
                </value>
                <value>
                    <fullName>Scholarship</fullName>
                </value>
                <value>
                    <fullName>Sponsor</fullName>
                </value>
                <value>
                    <fullName>Discount</fullName>
                </value>
                <value>
                    <fullName>Discount %</fullName>
                </value>
                <value>
                    <fullName>Refund</fullName>
                </value>
                <value>
                    <fullName>Credit Note</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ledger Entry</label>
    <nameField>
        <displayFormat>LE-{000000}</displayFormat>
        <label>Ledger Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/config/ready/19_Student_Ledger/objects/redu_Student_Ledger__c.object
<CustomObject>
    <label>Student Ledger</label>
    <nameField>
        <displayFormat>SL-{000000}</displayFormat>
        <label>Student Ledger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Ledgers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/config/ready/19_Student_Ledger/classes/redu_PAYMENT_LedgerEntry_TDTM.cls
/**
* @author           WDCi-LKoh (Original by: ???)
* @date             Oct 2020
* @group            Ledger Entry Automation for Payment
* @description      Create and Update Ledger Entry based on Payments activity
* @change-history   
*/
global class redu_PAYMENT_LedgerEntry_TDTM extends hed.TDTM_Runnable {
   	
    private static Set<Id> paymentIdSet;

    // the Trigger Handler’s Run method we must provide
   	global override hed.TDTM_Runnable.DmlWrapper run(List<SObject> newlist, List<SObject> oldlist, hed.TDTM_Runnable.Action triggerAction, Schema.DescribeSObjectResult objResult) {

        if (paymentIdSet == null) {
            paymentIdSet = new Set<Id>();
        }

        hed.TDTM_Runnable.dmlWrapper dmlWrapper = new hed.TDTM_Runnable.DmlWrapper();
        
        if (triggerAction == hed.TDTM_Runnable.Action.AfterInsert) {
            // Map from ids to payments
            Map<Id, rio_ed__Fee_Payment__c> paymentIdMap = new Map<Id, rio_ed__Fee_Payment__c>();
            
            // For each inserted payment, get its associated student ledger
            Map<Id, Id> paymentLedgerMap = new Map<Id, Id>();
            
             for (rio_ed__Fee_Payment__c payment : (List<rio_ed__Fee_Payment__c>)newList) {
                paymentIdMap.put(payment.Id, payment);
            }
        
            for (rio_ed__Fee_Payment__c pl : [
                SELECT Id, rio_ed__Student_Fee__r.rio_ed__Program_Enrollment__r.hed__Contact__r.redu_Student_Ledger__c
                FROM rio_ed__Fee_Payment__c 
                WHERE Id in :newlist])
            {
                paymentLedgerMap.put(pl.Id, pl.rio_ed__Student_Fee__r.rio_ed__Program_Enrollment__r.hed__Contact__r.redu_Student_Ledger__c);
            }
            
            // For each inserted payment, create a new ledger entry under its associated ledger
            List<redu_Ledger_Entry__c> newLedgerEntries = new List<redu_Ledger_Entry__c>();
            for (rio_ed__Fee_Payment__c payment : (list<rio_ed__Fee_Payment__c>)newlist) {
               	
                Id ledgerId = paymentLedgerMap.get(payment.Id);
                
                if (ledgerId != null) {
                    // Determine the type of ledger entry to be added (determined by payment type (Payment by default))
                    String ledgerEntryType = 'Payment';
                    
                    if (payment.rio_ed__Transaction_Type__c != null) {
                        ledgerEntryType = payment.rio_ed__Transaction_Type__c;
                    }
                    
                    redu_Ledger_Entry__c newLedgerEntry = new redu_Ledger_Entry__c(
                        redu_Student_Ledger__c = ledgerId, redu_Payment_Amount__c = payment.rio_ed__Payment_Amount__c,
                        redu_Date__c = payment.rio_ed__Payment_Date__c, redu_Related_Payment__c = payment.Id,
                        redu_Type__c = ledgerEntryType
                    );
                    newLedgerEntries.add(newLedgerEntry);
                }
           	}
            
            // Insert ledger entries and map errors back to any payments that may have caused them
            if (!newLedgerEntries.isEmpty()) {

                Database.SaveResult[] saveResultsLe = Database.insert(newLedgerEntries, false);
                for (Integer i = 0; i < saveResultsLe.size(); i++) {
                    //If the insert failed, map error back to triggering payment
                    if (!saveResultsLe[i].isSuccess()) {
                        paymentIdMap.get(newLedgerEntries[i].redu_Related_Payment__c).addError(saveResultsLe[i].getErrors()[0].getMessage());
                    }
                }
            }
        } else if (triggerAction == hed.TDTM_Runnable.Action.AfterUpdate) {
            // Map from ids to payments
            Map<Id, rio_ed__Fee_Payment__c> paymentIdMap = new Map<Id, rio_ed__Fee_Payment__c>();
            
            // For each updated payment, update its associated ledger entry
            List<redu_Ledger_Entry__c> entriesToUpdate = new List<redu_Ledger_Entry__c>();
            
            for (rio_ed__Fee_Payment__c payment : (list<rio_ed__Fee_Payment__c>)newlist) {
                paymentIdMap.put(payment.Id, payment);
            }
            
            for (redu_Ledger_Entry__c entryToUpdate : [
                SELECT redu_Related_Payment__r.rio_ed__Payment_Amount__c, redu_Related_Payment__r.rio_ed__Payment_Date__c, redu_Related_Payment__r.rio_ed__Transaction_Type__c 
                FROM redu_Ledger_Entry__c 
                WHERE redu_Related_Payment__c in :newlist]) 
            {
                // Determine the new type of the ledger entry (determined by payment type (Payment by default))
                String ledgerEntryType = 'Payment';
                
                if (entryToUpdate.redu_Related_Payment__r.rio_ed__Transaction_Type__c != null) {
                    ledgerEntryType = entryToUpdate.redu_Related_Payment__r.rio_ed__Transaction_Type__c;
                }
                
                entryToUpdate.redu_Payment_Amount__c = entryToUpdate.redu_Related_Payment__r.rio_ed__Payment_Amount__c;
                entryToUpdate.redu_Date__c = entryToUpdate.redu_Related_Payment__r.rio_ed__Payment_Date__c;
                entryToUpdate.redu_Type__c = ledgerEntryType;
                
                entriesToUpdate.add(entryToUpdate);
            }
            
            // Update ledger entries and map errors back to any payments that may have caused them
            if (!entriesToUpdate.isEmpty()) {                

                Database.SaveResult[] saveResultsLe = Database.update(entriesToUpdate, false);
                for (Integer i = 0; i < saveResultsLe.size(); i++) {
                    //If the update failed, map error back to triggering payment
                    if (!saveResultsLe[i].isSuccess()){
                        paymentIdMap.get(entriesToUpdate[i].redu_Related_Payment__c).addError(saveResultsLe[i].getErrors()[0].getMessage());
                    }
                }
            }
        } else if (triggerAction == hed.TDTM_Runnable.Action.BeforeDelete) {
            // Map from ids to payments
            Map<Id, rio_ed__Fee_Payment__c> paymentIdMap = new Map<Id, rio_ed__Fee_Payment__c>();
            
            // For each deleted payment, add its id to the map (used for error checking)
            for (rio_ed__Fee_Payment__c payment : (list<rio_ed__Fee_Payment__c>)oldList) {
                paymentIdMap.put(payment.Id, payment);
            }
            
            // For each deleted payment, delete its associated ledger entry
            List<redu_Ledger_Entry__c> entriesToDelete = [select Id, redu_Related_Payment__c from redu_Ledger_Entry__c where redu_Related_Payment__c IN :oldList];
            
            // Delete ledger entries and map errors back to any payments that may have caused them
            if (!entriesToDelete.isEmpty()){
                Database.DeleteResult[] deleteResultsLe = Database.delete(entriesToDelete, false);
                for (Integer i = 0; i < deleteResultsLe.size(); i++){
                    //If the delete failed, map error back to triggering payment
                    if (!deleteResultsLe[i].isSuccess()){
                        paymentIdMap.get(entriesToDelete[i].redu_Related_Payment__c).addError(deleteResultsLe[i].getErrors()[0].getMessage());
                    }
                }
            }
        }
        
        return dmlWrapper;
    }

    //────────────────────────────────────────────────────┐
    // TDTM Setting Installer
    //────────────────────────────────────────────────────┘
    public static void installTDTMSetting() {
        List<hed__Trigger_Handler__c> currentTriggerHandlerList = [
            SELECT Id, hed__Active__c, rio_ed__Unique_Key__c, hed__Object__c, hed__Load_Order__c, hed__Trigger_Action__c, hed__Class__c
            FROM hed__Trigger_Handler__c 
            WHERE hed__Active__c = true AND rio_ed__Unique_Key__c = 'rio_ed__Fee_Payment__c_redu_PAYMENT_LedgerEntry_TDTM_1'
        ];
        if (currentTriggerHandlerList.isEmpty()) {
            hed__Trigger_Handler__c newTriggerHandler = new hed__Trigger_Handler__c(
                Name = 'REDU_PAYMENT_LedgerEntry',
                hed__Object__c = 'rio_ed__Fee_Payment__c',
                hed__Load_Order__c = 1,
                hed__Trigger_Action__c = 'BeforeDelete;AfterInsert;AfterUpdate',
                hed__Class__c = 'redu_PAYMENT_LedgerEntry_TDTM',
                hed__Active__c = true,
                hed__User_Managed__c = true,
                rio_ed__Unique_Key__c = 'rio_ed__Fee_Payment__c_redu_PAYMENT_LedgerEntry_TDTM_1'
            );
            insert newTriggerHandler;
        }
    }
}