unpackaged/config/ready/06_Payment2us/objects/AAkPay__Payment_Txn__c.object
<CustomObject>
</CustomObject>

unpackaged/config/ready/StudentID/objects/Contact.object
<CustomObject>
</CustomObject>

unpackaged/post/06_standard_object_tracking/objects/Contact.object
    <fields>
        <fullName>rio_ed__Student_ID__c</fullName>
        <inlineHelpText>This is the Student ID generated by this Institution for this Student</inlineHelpText>
        <label>Student ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>

unpackaged/config/ready/15_Calls/objects/hed__Course__c.object
<CustomObject>
</CustomObject>

unpackaged/post/07_heda_object_tracking/objects/hed__Course_Offering__c.object
<CustomObject>
    <description>Joins Courses and Terms to contain information related to a single occurrence of a Course.</description>
	<label>Course Offering</label>
    <nameField>
        <label>Course Offering ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Offerings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
	<fields>
        <fullName>hed__Term__c</fullName>
        <description>Lookup to the Term record that represents when this Course Offering takes place.</description>
        <label>Term</label>
        <referenceTo>hed__Term__c</referenceTo>
        <relationshipLabel>Course Offerings</relationshipLabel>
        <relationshipName>Course_Offerings</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>hed__End_Date__c</fullName>
        <description>The date of the last session for this Course Offering.</description>
        <inlineHelpText>The date of the last session for this Course Offering.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>hed__Start_Date__c</fullName>
        <description>The date of the first session for this Course Offering.</description>
        <inlineHelpText>The date of the first session for this Course Offering.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>rio_ed__Fee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Will be automatically set based on Fee Label and Course &quot;use default fee&quot; settings</inlineHelpText>
        <label>Fee</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>Only a Fee that has a Fee Unit of Course or Credit can be added to a Course record.</errorMessage>
            <filterItems>
                <field>rio_ed__Fee__c.rio_ed__Fee_Unit__c</field>
                <operation>equals</operation>
                <value>Course</value>
            </filterItems>
            <filterItems>
                <field>rio_ed__Fee__c.rio_ed__Fee_Unit__c</field>
                <operation>equals</operation>
                <value>Credit</value>
            </filterItems>
            <infoMessage>Please select a Fee for this Course.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>rio_ed__Fee__c</referenceTo>
        <relationshipLabel>Course Offerings</relationshipLabel>
        <relationshipName>Course_Offerings</relationshipName>
        <type>Lookup</type>
    </fields>
	
</CustomObject>

unpackaged/post/02_heda_objects_ui/objects/hed__Course_Offering__c.object
    <fields>
        <fullName>hed__Course__c</fullName>
        <label>Course</label>
        <referenceTo>hed__Course__c</referenceTo>
        <relationshipLabel>Course Offerings</relationshipLabel>
        <relationshipName>Course_Offerings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>

unpackaged/config/sharing/00_orgwide_default_sharing/objects/hed__Plan_Requirement__c.object
<CustomObject>
    <description>The various course requirements for completing a Program Plan.</description>
	<label>Plan Requirement</label>
    <nameField>
        <label>Plan Requirement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan Requirements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/config/ready/StudentRequest/objects/hed__Program_Plan__c.object
<CustomObject>

</CustomObject>

unpackaged/post/02_heda_objects_ui/objects/hed__Term__c.object
<CustomObject>
    <description>Unit of time in which academic activities are taking place.</description>
    
    
    <label>Term</label>
    <nameField>
        <label>Term Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    
</CustomObject>

unpackaged/config/upgrade/upgrade - v2.11/02_custompicklist/objects/rio_ed__Fee__c.object
<CustomObject>
    <fields>
        <fullName>rio_ed__Fee_Type__c</fullName>
        <label>Fee Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Tuition</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Fee Group</fullName>
                </value>
                <value>
                    <fullName>Student Services &amp; Amenities</fullName>
                    <isActive>false</isActive>
                    <label>Student Services &amp; Amenities</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>rio_ed__Fee_Unit__c</fullName>
        <inlineHelpText>EFTSL: Equivalent Full-Time Student Load (i.e. full-time study load for 1 academic year).</inlineHelpText>
        <label>Fee Unit</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>rio_ed__Fee_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>EFTSL</fullName>
                </value>
                <value>
                    <fullName>Course</fullName>
                </value>
                <value>
                    <fullName>Program</fullName>
                </value>
                <value>
                    <fullName>Year</fullName>
                </value>
                <value>
                    <fullName>Term</fullName>
                </value>
                <value>
                    <fullName>Item</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

unpackaged/config/ready/03_FeeLine/objects/rio_ed__Fee_Schedule__c.object
<CustomObject>
</CustomObject>

unpackaged/config/ready/06_Payment2us/objects/rio_ed__Order__c.object
<CustomObject>
</CustomObject>

unpackaged/post/08_redu_object_tracking/objects/rio_ed__Order__c.object
    <fields>
        <fullName>rio_ed__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Pending Payment</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Void</fullName>
                </value>
                <value>
                    <fullName>Refunded</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

unpackaged/post/08_redu_object_tracking/objects/rio_ed__Order_Line__c.object
<CustomObject>
    <fields>
        <fullName>rio_ed__Order__c</fullName>
        <label>RIO Order</label>
        <referenceTo>rio_ed__Order__c</referenceTo>
        <relationshipLabel>Order Lines</relationshipLabel>
        <relationshipName>Order_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>rio_ed__Quantity__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>rio_ed__Unit_Price__c</fullName>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>RIO Order Line</label>
    <nameField>
        <displayFormat>OL-{00000}</displayFormat>
        <label>Order Line #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/unpackaged/post/upgrade - v2.5/01_layouts_and_configs/objects/rio_ed__Program_Pathway__c.object
<CustomObject>
</CustomObject>

unpackaged/config/ready/StudentRequest/objects/rio_ed__RIO_Education_Settings__c.object
<CustomObject>
</CustomObject>

unpackaged/config/ready/06_Payment2us/classes/redu_PTXN_UpdateOrder_TEST.cls
/**
 * @author 		    WDCi (VTan)
 * @date 		    Jan 2025
 * @group 		    Test
 * @description	    Test class for redu_PTXN_UpdateOrder_TDTM
 * 
 */

 @IsTest
 public with sharing class redu_PTXN_UpdateOrder_TEST {

    @TestSetup
    static void setupData() {        

        redu_PaymentTestDataFactory_UTIL.setupPayment2UsData();

        rio_ed__RIO_Education_Settings__c defaultSetting = redu_PaymentTestDataFactory_UTIL.createDefaultSettings();
        redu_PaymentTestDataFactory_UTIL.createDefaultUser(defaultSetting);
        insert defaultSetting;

        redu_PaymentCustomSetting_UTIL.getPaymentRecordTypeId();
        redu_PaymentCustomSetting_UTIL.getPaymentTrxDefaultStatus();

        redu_PaymentTriggerHandler_MANAGER.initCustomTriggerHandler();

        //Create Trigger Handler
        // first retrieve default EDA trigger handlers
        List<hed.TDTM_Global_API.TdtmToken> tokens = hed.TDTM_Global_API.getTdtmConfig();

        //Create RIO Ed trigger handlers using global method        
        rio_ed.REDU_PostInstallation rpi = new rio_ed.REDU_PostInstallation();
        rpi.createAllTriggerHandlers();                

        // Pass trigger handler config to set method for this test run
        hed.TDTM_Global_API.setTdtmConfig(tokens);

        //Create Educational Instituition
        List<Account> educationalInstitutions = redu_PaymentTestDataFactory_UTIL.createEducationalInstitutions(1);
        insert educationalInstitutions;

        //Create University Department
        List<Account> uniDepts = redu_PaymentTestDataFactory_UTIL.createUniversityDepartments(educationalInstitutions, 1);
        insert uniDepts;

        //Create Program
        List<Account> programList = redu_PaymentTestDataFactory_UTIL.createAcademicPrograms(uniDepts, 1);
        insert programList;


        //Create Term
        List<hed__Term__c> termList = redu_PaymentTestDataFactory_UTIL.createTerms(educationalInstitutions[0].Id, 1);
        termList[0].rio_ed__Census_Date__c = system.today();
        termList[0].hed__Type__c = 'Study Period';
        insert termList;

        //Create Fees
        Decimal TUITION_FEE_AMOUNT = 300;

        //Create Fees
        List<rio_ed__Fee__c> feeList = new List<rio_ed__Fee__c>();
        rio_ed__Fee__c tuitionFee = new rio_ed__Fee__c();
        tuitionFee.Name = 'tuitionFee';
        tuitionFee.rio_ed__Fee_Type__c = 'Tuition';
        tuitionFee.rio_ed__Fee_Unit__c = 'Course';
        tuitionFee.rio_ed__Description__c = 'Tuition Fee Description';
        feeList.add(tuitionFee);
        insert feeList;

        //Create Fee Schedules
        List<rio_ed__Fee_Schedule__c> feeScheduleList = new List<rio_ed__Fee_Schedule__c>();
        for (rio_ed__Fee__c fee : feeList){
            if (fee.rio_ed__Fee_Type__c != 'Fee Group'){
                rio_ed__Fee_Schedule__c fs = new rio_ed__Fee_Schedule__c();
                fs.Name = fee.Name + ' Fs';
                fs.rio_ed__Fee__c = fee.Id;
                fs.rio_ed__Fee_Start_Date__c = termList[0].hed__Start_Date__c;
                fs.rio_ed__Fee_End_Date__c = termList[0].hed__End_Date__c;
                fs.rio_ed__Current__c = true;
                if (fee.Name.contains('tuitionFee')){
                    fs.rio_ed__Fee_Amount_Domestic__c = TUITION_FEE_AMOUNT;
                }
                fs.rio_ed__Fee_Amount_International__c = fs.rio_ed__Fee_Amount_Domestic__c + 1;
                feeScheduleList.add(fs);
            }
            
        }
        insert feeScheduleList;

        //Create Fee Schedule Terms
        List<rio_ed__Fee_Schedule_Term__c> fstList = new List<rio_ed__Fee_Schedule_Term__c>();
        for (rio_ed__Fee_Schedule__c fs : feeScheduleList){
            for (hed__Term__c term : termList){
                rio_ed__Fee_Schedule_Term__c fst = new rio_ed__Fee_Schedule_Term__c();
                fst.rio_ed__Fee_Schedule__c = fs.Id;
                fst.rio_ed__Term__c = term.Id;
                fstList.add(fst);
            }
            
        }
        insert fstList;

        //Create Courses
        List<hed__Course__c> courseList = redu_PaymentTestDataFactory_UTIL.createCourses(new List<Id>{uniDepts[0].Id}, 2);
        for (hed__Course__c c : courseList){
            c.rio_ed__Fee__c = tuitionFee.Id;
        }
        insert courseList;

        //Create Course Offerings
        List<hed__Course_Offering__c> courseOfferingList = redu_PaymentTestDataFactory_UTIL.createCourseOfferings(courseList, termList[0]);
        insert courseOfferingList;

        //Create Program Plan(s)
        List<hed__Program_Plan__c> ppList = redu_PaymentTestDataFactory_UTIL.createProgramPlans(programList, termList[0]);        
        insert ppList;

        //Create Plan Requrements
        List<hed__Plan_Requirement__c> groupPlanReqs = redu_PaymentTestDataFactory_UTIL.createParentPlanRequirements(ppList, 1, 'Required', 10);
        insert groupPlanReqs;
        List<hed__Plan_Requirement__c> coursePlanReqs = redu_PaymentTestDataFactory_UTIL.createPlanRequirements(groupPlanReqs[0], courseList, 'Required', 10);
        insert coursePlanReqs;

        //Create Program Pathway
        List<rio_ed__Program_Pathway__c> progPathwayList = redu_PaymentTestDataFactory_UTIL.createProgramPathways('Pathway', 1, ppList, 'Full-time');
        insert progPathwayList;

        //Create Pathway Units
        List<rio_ed__Pathway_Unit__c> pathwayUnitList = new List<rio_ed__Pathway_Unit__c>();
        pathwayUnitList.addAll(redu_PaymentTestDataFactory_UTIL.createPathwayUnits(null, 1, coursePlanReqs[0].Id, new List<rio_ed__Program_Pathway__c>{progPathwayList[0]}, null));
        pathwayUnitList.addAll(redu_PaymentTestDataFactory_UTIL.createPathwayUnits(null, 1, coursePlanReqs[1].Id, new List<rio_ed__Program_Pathway__c>{progPathwayList[0]}, null));
        insert pathwayUnitList;
        
        //Create Student
        Contact newStudent = new Contact();
        newStudent.FirstName = 'redu_PayByCreditCard_TEST';
        newStudent.LastName = 'redu_PayByCreditCard_TEST';
        newStudent.Email = 'redu_PayByCreditCard_TEST@fakeemail.com';
        newStudent.hed__Preferred_Email__c = redu_PaymentConstant_UTIL.PREFERREDEMAIL_ALTERNATE;
        newStudent.hed__AlternateEmail__c = newStudent.Email;
        newStudent.rio_ed__Student_ID__c = '202112346';
        insert newStudent;
    }

    private static testMethod void runTest() {                

        Contact studentCon = [SELECT Id, AccountId FROM Contact LIMIT 1];

        rio_ed__Order__c ceOrder = new rio_ed__Order__c();
        ceOrder.rio_ed__Order_Date__c = Date.today();
        ceOrder.rio_ed__Account__c = studentCon.AccountId;
        ceOrder.rio_ed__Contact__c = studentCon.Id;
        ceOrder.rio_ed__Status__c = redu_PaymentConstant_UTIL.ORDER_STATUS_DRAFT;
        ceOrder.rio_ed__Description__c = 'CE Registration';
        insert ceOrder;

        rio_ed__Order_Line__c ceOrderLine = new rio_ed__Order_Line__c();
        ceOrderLine.rio_ed__Order__c = ceOrder.Id;
        ceOrderLine.rio_ed__Quantity__c = 1;
        ceOrderLine.rio_ed__Unit_Price__c = 1000;
        ceOrderLine.rio_ed__Description__c = 'BUS101';
        insert ceOrderLine;

        Test.startTest();

        Map<Id, rio_ed__Order__c> orderMapCheck = redu_Payment_UTIL.getOrdersInfo(new Set<Id>{ceOrder.Id});

        System.assert(!orderMapCheck.isEmpty(), 'No Order generated for redu_PTXN_UpdateOrder_TDTM testing');

        redu_PrePaymentInfo ppInfo = new redu_PrePaymentInfo(orderMapCheck.get(ceOrder.Id));

        // Generate Payment Transaction        
        AAkPay__Payment_Txn__c newTrx = redu_Payment_UTIL.initPaymentTrx(ppInfo, 1000);
        newTrx.OwnerId = UserInfo.getUserId();
        insert newTrx;

        // Simulating a paid payment transaction
        update newTrx;

        // Once the Payment Transaction is generated, check if the automatic Payment is generated
        List<rio_ed__Order__c> checkOrder = 
            [SELECT Id, rio_ed__Status__c 
                FROM rio_ed__Order__c WHERE Id =: ceOrder.Id];

        System.assert(!checkOrder.isEmpty(), 'No Order is generated');
        System.assert(checkOrder[0].rio_ed__Status__c == redu_PaymentConstant_UTIL.ORDER_STATUS_PAID, 'Order should be updated to Paid');        

        Test.stopTest();        
    }
}