unpackaged/config/ready/06_Payment2us/objects/AAkPay__Payment_Txn__c.object
<CustomObject>
    <fields>
        <fullName>redu_Payment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment</label>
        <referenceTo>rio_ed__Fee_Payment__c</referenceTo>
        <relationshipLabel>P2U Payment Txns</relationshipLabel>
        <relationshipName>Payment_Txns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>redu_Student_Fee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student Fee</label>
        <referenceTo>rio_ed__Student_Fee__c</referenceTo>
        <relationshipLabel>P2U Payment Txns</relationshipLabel>
        <relationshipName>Payment_Txns</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

unpackaged/post/02_heda_objects_ui/objects/hed__Trigger_Handler__c.object
<CustomObject>
    <description>Stores which classes to run in response to DML performed on an object.</description>
    <fields>
        <fullName>hed__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates that this module is active</description>
        <inlineHelpText>Indicates that this module is active</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>hed__Class__c</fullName>
        <description>Name of the class to be run</description>
        <inlineHelpText>Name of the class to be run</inlineHelpText>
        <label>Class</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>hed__Load_Order__c</fullName>
        <description>Order in which this module should be run, helps maintain dependencies in the modules and data.</description>
        <inlineHelpText>Order in which this module should be run, helps maintain dependencies in the modules and data.</inlineHelpText>
        <label>Load Order</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>hed__Object__c</fullName>
        <description>Name of the object this handler should be run for</description>
        <inlineHelpText>Name of the object this handler should be run for</inlineHelpText>
        <label>Object</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>hed__Trigger_Action__c</fullName>
        <description>Trigger Action in which this module should fire</description>
        <inlineHelpText>Trigger Action in which this module should fire</inlineHelpText>
        <label>Trigger Action</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BeforeInsert</fullName>
                </value>
                <value>
                    <fullName>BeforeUpdate</fullName>
                </value>
                <value>
                    <fullName>BeforeDelete</fullName>
                </value>
                <value>
                    <fullName>AfterInsert</fullName>
                </value>
                <value>
                    <fullName>AfterUpdate</fullName>
                </value>
                <value>
                    <fullName>AfterDelete</fullName>
                </value>
                <value>
                    <fullName>AfterUndelete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>hed__User_Managed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The record is managed by the user and updates won&apos;t be pushed to it.</description>
        <inlineHelpText>Check it if you intent to manage the record yourself. Be aware that updates to the package won&apos;t update the record.</inlineHelpText>
        <label>User Managed</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger Handler</label>
    <nameField>
        <label>Trigger Handler Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trigger Handlers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/config/ready/03_FeeLine/objects/rio_ed__Fee_Line__c.object
<CustomObject>
</CustomObject>

unpackaged/config/ready/Payment2us/objects/rio_ed__Student_Fee__c.object
<CustomObject>
</CustomObject>

unpackaged/config/ready/06_Payment2us/classes/redu_PTXN_UpsertPayment_TDTM.cls
/**
 * @author 		    WDCi (LKoh)
 * @date 		    Jan 2022
 * @group 		    Student Fee
 * @description	    Custom Trigger to create a rio ed payment record when payments2us's payment transaction record is paid
 * 
 */

global without sharing class redu_PTXN_UpsertPayment_TDTM extends hed.TDTM_Runnable {
    
    /**
     * @description Trigger Handler on rio_ed__Student_Fee__c to handle setting the Program Plan
     * @param newList the list of rio_ed__Student_Fee__c from trigger new
     * @param oldList the list of rio_ed__Student_Fee__c from trigger old
     * @param triggerAction which trigger event (BeforeInsert, AfterInsert, etc.).
     * @param objResult the describe for rio_ed__Student_Fee__c
     * @return DmlWrapper
     */
    public override DmlWrapper run(List<SObject> newList, 
                                   List<SObject> oldList, 
                                   hed.TDTM_Runnable.Action triggerAction, 
                                   Schema.DescribeSObjectResult objResult) {

        System.debug('redu_PTXN_UpsertPayment_TDTM running...');

        hed.TDTM_Runnable.DmlWrapper dmlWrapper = null;

        if(triggerAction == hed.TDTM_Runnable.Action.BeforeUpdate){
            List<AAkPay__Payment_Txn__c> qualifiedList = new List<AAkPay__Payment_Txn__c>();

            integer counter = 0;
            for(AAkPay__Payment_Txn__c pTxn : (List<AAkPay__Payment_Txn__c>) newList ){
                AAkPay__Payment_Txn__c oldPTxn = (AAkPay__Payment_Txn__c) oldList.get(counter);

                if((pTxn.redu_Student_Fee__c != null && pTxn.redu_Payment__c == null && pTxn.AAkPay__Banked_Payment__c == 'YES' && pTxn.AAkPay__Banked_Payment__c != oldPTxn.AAkPay__Banked_Payment__c)
                    || (pTxn.redu_Student_Fee__c != null && Test.isRunningTest())) {
                    qualifiedList.add(pTxn);
                }
            }            

            Map<Integer, Integer> mapFeeline2PaymentIdx = new Map<Integer, Integer>();
            
            if(!qualifiedList.isEmpty()){
                List<rio_ed__Fee_Payment__c> reduPayments = new List<rio_ed__Fee_Payment__c>();
                List<rio_ed__Fee_Line__c> reduFeelines = new List<rio_ed__Fee_Line__c>();
                integer dmlCounter = 0;                
                
                for(AAkPay__Payment_Txn__c pTxn : qualifiedList){
                   
                    rio_ed__Fee_Payment__c feePayment = redu_Payment_UTIL.initFeePayment(
                                                            pTxn.redu_Student_Fee__c, 
                                                            pTxn.AAkPay__Card_Charged_Amount__c, 
                                                            pTxn.AAkPay__Transaction_Date__c, 
                                                            pTxn.AAkPay__Payment_Source__c);
                    feePayment.rio_ed__Transaction_Type__c = redu_PaymentConstant_UTIL.FP_TRANSACTIONTYPE_PAYMENT;
                    reduPayments.add(feePayment);
                    
                    if (pTxn.AAkPay__Service_Fee__c > 0){                       
                        // Add a Fee-line to track service fee
                        rio_ed__Fee_Line__c flSvc = new rio_ed__Fee_Line__c(rio_ed__Student_Fee__c = pTxn.redu_Student_Fee__c, rio_ed__Other_Amount__c = pTxn.AAkPay__Service_Fee__c);
                        mapFeeline2PaymentIdx.put(reduFeelines.size(), dmlCounter);
                        reduFeelines.add(flSvc);
                    }
                    dmlCounter++;
                }

                System.debug('reduPayments:');
                System.debug(reduPayments);

                Set<Id> paymentIds = new Set<Id>();
                dmlCounter = 0;
                for(Database.SaveResult sr : Database.insert(reduPayments, false)){
                    if(!sr.isSuccess()) {
                        System.debug('Error in Payment Record creation:');
                        System.debug(sr.getErrors()[0].getMessage());
                        (qualifiedList.get(dmlCounter)).addError(sr.getErrors()[0].getMessage());
                    } else {
                        AAkPay__Payment_Txn__c pTxn = qualifiedList.get(dmlCounter);
                        pTxn.redu_Payment__c = sr.getId();

                        paymentIds.add(pTxn.redu_Payment__c);
                    }

                    dmlCounter ++;
                }                
                
                // Insert Fee lines for service amounts if applicable
                dmlCounter = 0;
                if (reduFeelines.size()>0){
                    
                    for(Database.SaveResult sr : Database.insert(reduFeelines, false)){
                        if(!sr.isSuccess()){
                            qualifiedList.get(mapFeeline2PaymentIdx.get(dmlCounter)).addError(sr.getErrors()[0].getMessage());
                        }                    
                        dmlCounter++;
                    }
                }
            }
        }

        return dmlWrapper;
    }

    //────────────────────────────────────────────────────┐
    // TDTM Setting Installer
    //────────────────────────────────────────────────────┘
    public static void installTDTMSetting() {
        List<hed__Trigger_Handler__c> currentTriggerHandlerList = 
            [SELECT Id, hed__Active__c, rio_ed__Unique_Key__c, hed__Object__c, hed__Load_Order__c, hed__Trigger_Action__c, hed__Class__c
                FROM hed__Trigger_Handler__c 
                WHERE hed__Active__c = true AND rio_ed__Unique_Key__c = 'AAkPay__Payment_Txn__c_redu_PTXN_UpsertPayment_TDTM_1'];
        if (currentTriggerHandlerList.isEmpty()) {
            hed__Trigger_Handler__c newTriggerHandler = new hed__Trigger_Handler__c(
                Name = 'RIOREADY_UpsertPayment',
                hed__Object__c = 'AAkPay__Payment_Txn__c',
                hed__Load_Order__c = 1,
                hed__Trigger_Action__c = 'BeforeUpdate',
                hed__Class__c = 'redu_PTXN_UpsertPayment_TDTM',
                hed__Active__c = true,
                hed__User_Managed__c = true,
                rio_ed__Unique_Key__c = 'AAkPay__Payment_Txn__c_redu_PTXN_UpsertPayment_TDTM_1'
            );
            insert newTriggerHandler;
        }
    }
}