unpackaged/config/ready/06_Payment2us/objects/AAkPay__Payment_Txn__c.object
<CustomObject>
    <fields>
        <fullName>redu_RIO_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RIO Order</label>
        <referenceTo>rio_ed__Order__c</referenceTo>
        <relationshipLabel>Payment Txns</relationshipLabel>
        <relationshipName>Payment_Txns</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

unpackaged/post/02_heda_objects_ui/objects/hed__Trigger_Handler__c.object
<CustomObject>
    <description>Stores which classes to run in response to DML performed on an object.</description>
    <fields>
        <fullName>hed__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates that this module is active</description>
        <inlineHelpText>Indicates that this module is active</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>hed__Class__c</fullName>
        <description>Name of the class to be run</description>
        <inlineHelpText>Name of the class to be run</inlineHelpText>
        <label>Class</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>hed__Load_Order__c</fullName>
        <description>Order in which this module should be run, helps maintain dependencies in the modules and data.</description>
        <inlineHelpText>Order in which this module should be run, helps maintain dependencies in the modules and data.</inlineHelpText>
        <label>Load Order</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>hed__Object__c</fullName>
        <description>Name of the object this handler should be run for</description>
        <inlineHelpText>Name of the object this handler should be run for</inlineHelpText>
        <label>Object</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>hed__Trigger_Action__c</fullName>
        <description>Trigger Action in which this module should fire</description>
        <inlineHelpText>Trigger Action in which this module should fire</inlineHelpText>
        <label>Trigger Action</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BeforeInsert</fullName>
                </value>
                <value>
                    <fullName>BeforeUpdate</fullName>
                </value>
                <value>
                    <fullName>BeforeDelete</fullName>
                </value>
                <value>
                    <fullName>AfterInsert</fullName>
                </value>
                <value>
                    <fullName>AfterUpdate</fullName>
                </value>
                <value>
                    <fullName>AfterDelete</fullName>
                </value>
                <value>
                    <fullName>AfterUndelete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>hed__User_Managed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The record is managed by the user and updates won&apos;t be pushed to it.</description>
        <inlineHelpText>Check it if you intent to manage the record yourself. Be aware that updates to the package won&apos;t update the record.</inlineHelpText>
        <label>User Managed</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger Handler</label>
    <nameField>
        <label>Trigger Handler Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trigger Handlers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/config/ready/06_Payment2us/objects/rio_ed__Order__c.object
<CustomObject>
</CustomObject>

unpackaged/post/08_redu_object_tracking/objects/rio_ed__Order__c.object
    <fields>
        <fullName>rio_ed__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Pending Payment</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Void</fullName>
                </value>
                <value>
                    <fullName>Refunded</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

unpackaged/config/ready/Payment2us/objects/rio_ed__Student_Fee__c.object
<CustomObject>
</CustomObject>

unpackaged/config/ready/06_Payment2us/classes/redu_PTXN_UpdateOrder_TDTM.cls
/**
 * @author 		    WDCi (VTan)
 * @date 		    Jan 2025
 * @group 		    Student Fee
 * @description	    Custom Trigger to update status of RIO Order when payments2us's payment transaction record is paid
 * 
 */
global without sharing class redu_PTXN_UpdateOrder_TDTM extends hed.TDTM_Runnable {

    /**
     * @description Trigger Handler on rio_ed__Student_Fee__c to handle setting the Program Plan
     * @param newList the list of rio_ed__Student_Fee__c from trigger new
     * @param oldList the list of rio_ed__Student_Fee__c from trigger old
     * @param triggerAction which trigger event (BeforeInsert, AfterInsert, etc.).
     * @param objResult the describe for rio_ed__Student_Fee__c
     * @return DmlWrapper
     */
    public override DmlWrapper run(List<SObject> newList, 
                                   List<SObject> oldList, 
                                   hed.TDTM_Runnable.Action triggerAction, 
                                   Schema.DescribeSObjectResult objResult) {

        hed.TDTM_Runnable.DmlWrapper dmlWrapper = null;
        if(triggerAction == hed.TDTM_Runnable.Action.AfterUpdate){

            Set<Id> orderIds = new Set<Id>();
            integer counter = 0;
            for(AAkPay__Payment_Txn__c pTxn : (List<AAkPay__Payment_Txn__c>) newList ){
                AAkPay__Payment_Txn__c oldPTxn = (AAkPay__Payment_Txn__c) oldList.get(counter);

                if((pTxn.redu_RIO_Order__c != null && pTxn.AAkPay__Banked_Payment__c == 'YES' && pTxn.AAkPay__Banked_Payment__c != oldPTxn.AAkPay__Banked_Payment__c)
                    || (pTxn.redu_RIO_Order__c != null && Test.isRunningTest())) {

                        orderIds.add(pTxn.redu_RIO_Order__c);
                }
                
                if(!orderIds.isEmpty()){

                    //Update RIO Order only if its drafted
                    List<rio_ed__Order__c> qualifiedOrders = new List<rio_ed__Order__c>();
                    for(rio_ed__Order__c order : [SELECT Id, rio_ed__Status__c 
                                                FROM rio_ed__Order__c 
                                                WHERE Id IN : orderIds AND rio_ed__Status__c = : redu_PaymentConstant_UTIL.ORDER_STATUS_DRAFT]){

                        order.rio_ed__Status__c = redu_PaymentConstant_UTIL.ORDER_STATUS_PAID;
                        qualifiedOrders.add(order);
                    }
                    
                    if(!qualifiedOrders.isEmpty()){
                        update qualifiedOrders;
                    }
                }
            }     
        }
        return dmlWrapper;
    }

    //────────────────────────────────────────────────────┐
    // TDTM Setting Installer
    //────────────────────────────────────────────────────┘
    public static void installTDTMSetting() {
        List<hed__Trigger_Handler__c> currentTriggerHandlerList = 
            [SELECT Id, hed__Active__c, rio_ed__Unique_Key__c, hed__Object__c, hed__Load_Order__c, hed__Trigger_Action__c, hed__Class__c
                FROM hed__Trigger_Handler__c 
                WHERE hed__Active__c = true AND rio_ed__Unique_Key__c = 'AAkPay__Payment_Txn__c_redu_PTXN_UpdateOrder_TDTM_2'];
        if (currentTriggerHandlerList.isEmpty()) {
            hed__Trigger_Handler__c newTriggerHandler = new hed__Trigger_Handler__c(
                Name = 'RIOREADY_UpdateOrder',
                hed__Object__c = 'AAkPay__Payment_Txn__c',
                hed__Load_Order__c = 1,
                hed__Trigger_Action__c = 'AfterUpdate',
                hed__Class__c = 'redu_PTXN_UpdateOrder_TDTM',
                hed__Active__c = true,
                hed__User_Managed__c = true,
                rio_ed__Unique_Key__c = 'AAkPay__Payment_Txn__c_redu_PTXN_UpdateOrder_TDTM_2'
            );
            insert newTriggerHandler;
        }
    }
}