unpackaged/post/06_standard_object_tracking/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>rio_ed__Student_ID__c</fullName>
        <inlineHelpText>This is the Student ID generated by this Institution for this Student</inlineHelpText>
        <label>Student ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

unpackaged/post/02_heda_objects_ui/objects/hed__Course__c.object
<CustomObject>
    <description>Academic course that a Department or School (the degree-granting Account type for the University) offers.</description>
    
    
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/pre/01_heda_object_tracking/objects/hed__Course_Enrollment__c.object
<CustomObject>
    <description>Represents a connection to a Course Offering.</description>
    <label>Course Connection</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Course Connection ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Connections</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/post/07_heda_object_tracking/objects/hed__Course_Enrollment__c.object
    <fields>
        <fullName>hed__Course_Offering__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Course Offering the student or faculty member is involved with.</description>
        <inlineHelpText>The Course Offering the student or faculty member is involved with.</inlineHelpText>
        <label>Course Offering ID</label>
        <referenceTo>hed__Course_Offering__c</referenceTo>
        <relationshipLabel>Course Connection</relationshipLabel>
        <relationshipName>Course_Enrollment</relationshipName>
        <type>Lookup</type>
    </fields>

unpackaged/post/07_heda_object_tracking/objects/hed__Course_Enrollment__c.object
    <fields>
        <fullName>rio_ed__Enrollment_Status__c</fullName>
        <label>Enrollment Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Enrollment Requested</fullName>
                </value>
                <value>
                    <fullName>Enrolled</fullName>
                </value>
                <value>
                    <fullName>Withdrawal Requested</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Withdrawn With Penalty</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Waitlisted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

unpackaged/post/07_heda_object_tracking/objects/hed__Course_Enrollment__c.object
    <fields>
        <fullName>rio_ed__Fee_Type__c</fullName>
        <inlineHelpText>How the student will pay for this course</inlineHelpText>
        <label>Fee Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>rio_ed__Fee_Type</valueSetName>
        </valueSet>
    </fields>

src/unpackaged/upgrade - v2.3/01_layouts_and_configs/objects/hed__Course_Enrollment__c.object
    <recordTypes>
        <fullName>Student</fullName>
        <active>true</active>
        <description>A Student Course Connection</description>
        <label>Student</label>
        
		
    </recordTypes>

unpackaged/post/07_heda_object_tracking/objects/hed__Course_Offering__c.object
<CustomObject>
    <description>Joins Courses and Terms to contain information related to a single occurrence of a Course.</description>
	<label>Course Offering</label>
    <nameField>
        <label>Course Offering ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Offerings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
	<fields>
        <fullName>hed__Term__c</fullName>
        <description>Lookup to the Term record that represents when this Course Offering takes place.</description>
        <label>Term</label>
        <referenceTo>hed__Term__c</referenceTo>
        <relationshipLabel>Course Offerings</relationshipLabel>
        <relationshipName>Course_Offerings</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>hed__End_Date__c</fullName>
        <description>The date of the last session for this Course Offering.</description>
        <inlineHelpText>The date of the last session for this Course Offering.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>hed__Start_Date__c</fullName>
        <description>The date of the first session for this Course Offering.</description>
        <inlineHelpText>The date of the first session for this Course Offering.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>rio_ed__Fee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Will be automatically set based on Fee Label and Course &quot;use default fee&quot; settings</inlineHelpText>
        <label>Fee</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>Only a Fee that has a Fee Unit of Course or Credit can be added to a Course record.</errorMessage>
            <filterItems>
                <field>rio_ed__Fee__c.rio_ed__Fee_Unit__c</field>
                <operation>equals</operation>
                <value>Course</value>
            </filterItems>
            <filterItems>
                <field>rio_ed__Fee__c.rio_ed__Fee_Unit__c</field>
                <operation>equals</operation>
                <value>Credit</value>
            </filterItems>
            <infoMessage>Please select a Fee for this Course.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>rio_ed__Fee__c</referenceTo>
        <relationshipLabel>Course Offerings</relationshipLabel>
        <relationshipName>Course_Offerings</relationshipName>
        <type>Lookup</type>
    </fields>
	
</CustomObject>

unpackaged/post/02_heda_objects_ui/objects/hed__Course_Offering__c.object
    <fields>
        <fullName>hed__Course__c</fullName>
        <label>Course</label>
        <referenceTo>hed__Course__c</referenceTo>
        <relationshipLabel>Course Offerings</relationshipLabel>
        <relationshipName>Course_Offerings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>

unpackaged/post/02_eda_objects_ui/objects/hed__Plan_Requirement__c.object
<CustomObject>
    <description>The various course requirements for completing a Program Plan.</description>
    
    <label>Plan Requirement</label>
    <nameField>
        <label>Plan Requirement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan Requirements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/ready/Withdrawal/objects/hed__Program_Enrollment__c.object
<CustomObject>
</CustomObject>

unpackaged/post/07_heda_object_tracking/objects/hed__Program_Enrollment__c.object
    <fields>
        <fullName>hed__End_Date__c</fullName>
        <description>The date the student is scheduled to complete the Program.</description>
        <inlineHelpText>The date the student is scheduled to complete the Program.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>

unpackaged/post/07_heda_object_tracking/objects/hed__Program_Enrollment__c.object
    <fields>
        <fullName>hed__Start_Date__c</fullName>
        <description>The date the student started, or is expected to start, this Program.</description>
        <inlineHelpText>The date the student started, or is expected to start, this Program.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>

unpackaged/upgrade/upgrade - v3.1/02_custompicklist/objects/hed__Program_Enrollment__c.object
    <fields>
        <fullName>rio_ed__Fee_Type__c</fullName>
        <label>Fee Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>rio_ed__Fee_Type</valueSetName>
        </valueSet>
    </fields>

unpackaged/sharing/00_orgwide_default_sharing/objects/hed__Program_Plan__c.object
<CustomObject>
    <description>Links Courses to an Academic Program to create a path for students to follow. An Academic Program can list multiple Courses, and a Course can be associated with multiple Academic Programs.</description>
	<label>Program Plan</label>
    <nameField>
        <label>Program Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/post/02_heda_objects_ui/objects/hed__Term__c.object
<CustomObject>
    <description>Unit of time in which academic activities are taking place.</description>
    
    
    <label>Term</label>
    <nameField>
        <label>Term Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    
</CustomObject>

unpackaged/upgrade/upgrade - v3.5/02_custompicklists/objects/rio_ed__Fee__c.object
<CustomObject>
    <fields>
        <fullName>rio_ed__Fee_Type__c</fullName>
        <label>Fee Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Tuition</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Fee Group</fullName>
                </value>
                <value>
                    <fullName>Application</fullName>
                </value>
                <value>
                    <fullName>Deposit</fullName>
                </value>
                <value>
                    <fullName>Student Services &amp; Amenities</fullName>
                    <isActive>false</isActive>
                    <label>Student Services &amp; Amenities</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>rio_ed__Fee_Unit__c</fullName>
        <inlineHelpText>EFTSL: Equivalent Full-Time Student Load (i.e. full-time study load for 1 academic year).</inlineHelpText>
        <label>Fee Unit</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>rio_ed__Fee_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>EFTSL</fullName>
                </value>
                <value>
                    <fullName>Course</fullName>
                </value>
                <value>
                    <fullName>Program</fullName>
                </value>
                <value>
                    <fullName>Year</fullName>
                </value>
                <value>
                    <fullName>Term</fullName>
                </value>
                <value>
                    <fullName>Item</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
                <value>
                    <fullName>Application</fullName>
                </value>
                <value>
                    <fullName>Deposit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

unpackaged/config/upgrade/19 - upgrade - v3.5/02_custompicklists/objects/rio_ed__Fee_Schedule__c.object
<CustomObject>
</CustomObject>

unpackaged/post/08_redu_object_tracking/objects/rio_ed__Program_Application__c.object
<CustomObject>
    <description>Records each Contact&apos;s Program application(s).</description>
    <fields>
        <fullName>rio_ed__Applicant__c</fullName>
        <inlineHelpText>The Contact who is applying to be enrolled in the Program.</inlineHelpText>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Program Applications</relationshipLabel>
        <relationshipName>Program_Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>rio_ed__Fee_Type__c</fullName>
        <inlineHelpText>How the student will pay for this course</inlineHelpText>
        <label>Fee Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>rio_ed__Fee_Type</valueSetName>
        </valueSet>
    </fields>
    <label>Program Application</label>
    <nameField>
        <displayFormat>PA-{00000}</displayFormat>
        <label>Program Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Applications</pluralLabel>
	<sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/unpackaged/post/upgrade - v2.5/01_layouts_and_configs/objects/rio_ed__Program_Pathway__c.object
<CustomObject>
</CustomObject>

unpackaged/config/ready/StudentRequest/objects/rio_ed__RIO_Education_Settings__c.object
<CustomObject>
</CustomObject>

unpackaged/config/ready/Payment2us/objects/rio_ed__Student_Fee__c.object
<CustomObject>
</CustomObject>

unpackaged/upgrade/upgrade - v2.9/02_custompicklist/globalValueSets/rio_ed__Fee_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Self Paid</fullName>
        <default>true</default>
        <label>Self Paid</label>
    </customValue>
    <customValue>
        <fullName>Financial Assistance</fullName>
    </customValue>
    <customValue>
        <fullName>Scholarship</fullName>
        <isActive>false</isActive>
        <label>Scholarship</label>
    </customValue>
    <customValue>
        <fullName>Sponsor</fullName>
        <isActive>false</isActive>
        <label>Sponsor</label>
    </customValue>
    <customValue>
        <fullName>Government Funding</fullName>
        <isActive>false</isActive>
        <label>Government Funding</label>
    </customValue>
    <masterLabel>Fee Type</masterLabel>
</GlobalValueSet>

unpackaged/ready/Payment2us/classes/redu_PrePaymentHandler_TEST.cls
/**
 * @author          WDCi-LKoh
 * @date            Jan 2022
 * @group           Payment
 * @description     TEST for Pre Payment component
 */
@IsTest global with sharing class redu_PrePaymentHandler_TEST {    

    @TestSetup
    static void setupData() {

        redu_PaymentTestDataFactory_UTIL.setupPayment2UsData();

        rio_ed__RIO_Education_Settings__c defaultSetting = redu_PaymentTestDataFactory_UTIL.createDefaultSettings();
        redu_PaymentTestDataFactory_UTIL.createDefaultUser(defaultSetting);
        insert defaultSetting;

        redu_PaymentTriggerHandler_MANAGER.initCustomTriggerHandler();

        //Create Trigger Handler
        // first retrieve default EDA trigger handlers
        List<hed.TDTM_Global_API.TdtmToken> tokens = hed.TDTM_Global_API.getTdtmConfig();

        //Create RIO Ed trigger handlers using global method        
        rio_ed.REDU_PostInstallation rpi = new rio_ed.REDU_PostInstallation();
        rpi.createAllTriggerHandlers();                

        // Pass trigger handler config to set method for this test run
        hed.TDTM_Global_API.setTdtmConfig(tokens);        
    }

    
    private static testMethod void runTest() {                

        //Create Educational Instituition
        List<Account> educationalInstitutions = redu_PaymentTestDataFactory_UTIL.createEducationalInstitutions(1);
        insert educationalInstitutions;

        //Create University Department
        List<Account> uniDepts = redu_PaymentTestDataFactory_UTIL.createUniversityDepartments(educationalInstitutions, 1);
        insert uniDepts;

        //Create Program
        List<Account> programList = redu_PaymentTestDataFactory_UTIL.createAcademicPrograms(uniDepts, 1);
        insert programList;


        //Create Term
        List<hed__Term__c> termList = redu_PaymentTestDataFactory_UTIL.createTerms(educationalInstitutions[0].Id, 1);
        insert termList;

        //Create Fees
        Decimal TUITION_FEE_AMOUNT = 300;

        //Create Fees
        List<rio_ed__Fee__c> feeList = new List<rio_ed__Fee__c>();
        rio_ed__Fee__c tuitionFee = new rio_ed__Fee__c();
        tuitionFee.Name = 'tuitionFee';
        tuitionFee.rio_ed__Fee_Type__c = 'Tuition';
        tuitionFee.rio_ed__Fee_Unit__c = 'Course';
        tuitionFee.rio_ed__Description__c = 'Tuition Fee Description';
        feeList.add(tuitionFee);
        insert feeList;

        //Create Fee Schedules
        List<rio_ed__Fee_Schedule__c> feeScheduleList = new List<rio_ed__Fee_Schedule__c>();
        for (rio_ed__Fee__c fee : feeList){
            if (fee.rio_ed__Fee_Type__c != 'Fee Group'){
                rio_ed__Fee_Schedule__c fs = new rio_ed__Fee_Schedule__c();
                fs.Name = fee.Name + ' Fs';
                fs.rio_ed__Fee__c = fee.Id;
                fs.rio_ed__Fee_Start_Date__c = termList[0].hed__Start_Date__c;
                fs.rio_ed__Fee_End_Date__c = termList[0].hed__End_Date__c;
                fs.rio_ed__Current__c = true;
                if (fee.Name.contains('tuitionFee')){
                    fs.rio_ed__Fee_Amount_Domestic__c = TUITION_FEE_AMOUNT;
                }
                fs.rio_ed__Fee_Amount_International__c = fs.rio_ed__Fee_Amount_Domestic__c + 1;
                feeScheduleList.add(fs);
            }
            
        }
        insert feeScheduleList;

        //Create Fee Schedule Terms
        List<rio_ed__Fee_Schedule_Term__c> fstList = new List<rio_ed__Fee_Schedule_Term__c>();
        for (rio_ed__Fee_Schedule__c fs : feeScheduleList){
            for (hed__Term__c term : termList){
                rio_ed__Fee_Schedule_Term__c fst = new rio_ed__Fee_Schedule_Term__c();
                fst.rio_ed__Fee_Schedule__c = fs.Id;
                fst.rio_ed__Term__c = term.Id;
                fstList.add(fst);
            }
            
        }
        insert fstList;

        //Create Courses
        List<hed__Course__c> courseList = redu_PaymentTestDataFactory_UTIL.createCourses(new List<Id>{uniDepts[0].Id}, 2);
        for (hed__Course__c c : courseList){
            c.rio_ed__Fee__c = tuitionFee.Id;
        }
        insert courseList;

        //Create Course Offerings
        List<hed__Course_Offering__c> courseOfferingList = redu_PaymentTestDataFactory_UTIL.createCourseOfferings(courseList, termList[0]);
        insert courseOfferingList;

        //Create Program Plan(s)
        List<hed__Program_Plan__c> ppList = redu_PaymentTestDataFactory_UTIL.createProgramPlans(programList, termList[0]);        
        insert ppList;

        //Create Plan Requrements
        List<hed__Plan_Requirement__c> groupPlanReqs = redu_PaymentTestDataFactory_UTIL.createParentPlanRequirements(ppList, 1, 'Required', 10);
        insert groupPlanReqs;
        List<hed__Plan_Requirement__c> coursePlanReqs = redu_PaymentTestDataFactory_UTIL.createPlanRequirements(groupPlanReqs[0], courseList, 'Required', 10);
        insert coursePlanReqs;

        //Create Program Pathway
        List<rio_ed__Program_Pathway__c> progPathwayList = redu_PaymentTestDataFactory_UTIL.createProgramPathways('Pathway', 1, ppList, 'Full-time');
        insert progPathwayList;

        //Create Pathway Units
        List<rio_ed__Pathway_Unit__c> pathwayUnitList = new List<rio_ed__Pathway_Unit__c>();
        pathwayUnitList.addAll(redu_PaymentTestDataFactory_UTIL.createPathwayUnits(null, 1, coursePlanReqs[0].Id, new List<rio_ed__Program_Pathway__c>{progPathwayList[0]}, null));
        pathwayUnitList.addAll(redu_PaymentTestDataFactory_UTIL.createPathwayUnits(null, 1, coursePlanReqs[1].Id, new List<rio_ed__Program_Pathway__c>{progPathwayList[0]}, null));
        insert pathwayUnitList;
        
        //Create Student
        Contact newStudent = new Contact();
        newStudent.FirstName = 'redu_PayByCreditCard_TEST';
        newStudent.LastName = 'redu_PayByCreditCard_TEST';
        newStudent.Email = 'redu_PayByCreditCard_TEST@fakeemail.com';
        newStudent.hed__Preferred_Email__c = redu_PaymentConstant_UTIL.PREFERREDEMAIL_ALTERNATE;
        newStudent.hed__AlternateEmail__c = newStudent.Email;
        newStudent.rio_ed__Student_ID__c = '202112346';
        insert newStudent;

        rio_ed__Program_Application__c newPA = new rio_ed__Program_Application__c();        
        newPA.rio_ed__Applicant__c = newStudent.Id;
        newPA.rio_ed__Starting_Term__c = termList[0].Id;
        insert newPA;

        //Create Program Enrollment
        hed__Program_Enrollment__c pe = new hed__Program_Enrollment__c();
        pe.hed__Contact__c = newStudent.Id;
        pe.hed__Program_Plan__c = ppList[0].Id;
        pe.rio_ed__Program_Pathway__c = progPathwayList[0].Id;
        pe.rio_ed__Fee_Method__c = 'Term';
        pe.rio_ed__Pay_Upfront__c = 'No';
        insert pe;

        //Make sure Course Connections were created
        List<hed__Course_Enrollment__c> ccList = [
            SELECT Id, rio_ed__Target_Course__c
            FROM hed__Course_Enrollment__c
            WHERE hed__Program_Enrollment__c = :pe.Id
        ];
        System.assertEquals(courseOfferingList.size(), ccList.size(), 'Incorrect number of Course Connections created');

        //Enroll in courses
            //Creating student fees
        for (hed__Course_Enrollment__c cc : ccList){
            for (hed__Course_Offering__c co : courseOfferingList){
                if (cc.rio_ed__Target_Course__c == co.hed__Course__c){
                    cc.hed__Course_Offering__c = co.Id;
                    cc.rio_ed__Enrollment_Status__c = 'Enrolled';
                    break;
                }
            }
        }

        update ccList;

        List<rio_ed__Student_Fee__c> studentFeeCheck = [SELECT Id, rio_ed__Outstanding_Amount__c FROM rio_ed__Student_Fee__c];        

        Test.startTest();

        Id studentFeeId = studentFeeCheck[0].Id;        

        redu_Payment_UTIL.returnEmpty = true;
        try {
            String messageCheck1 = redu_PrePaymentHandler_LCTRL.pageMessage(studentFeeId);
        } catch (Exception ex) {            
        }
        

        redu_Payment_UTIL.returnEmpty = false;
        String messageCheck2 = redu_PrePaymentHandler_LCTRL.pageMessage(studentFeeId);
        System.debug('messageCheck2:');
        System.debug(messageCheck2);
        
        // Case 1 - First Txn created for the Student Fee
        redu_PrePaymentInfo ppInfoCheck = redu_PrePaymentHandler_LCTRL.initData(studentFeeId, newPA.Id);
        System.debug('ppInfoCheck:');
        System.debug(ppInfoCheck);

        // Case 2 - Student Fee already has Payment Txn (from Case 1)
        redu_PrePaymentInfo ppInfoCheck2 = redu_PrePaymentHandler_LCTRL.initData(studentFeeId, newPA.Id);
        System.debug('ppInfoCheck2:');
        System.debug(ppInfoCheck2);

        try {
            // Case 3 - no Student Fee provided
            redu_PrePaymentInfo ppInfoCheck3 = redu_PrePaymentHandler_LCTRL.initData(null, null);
            System.debug('ppInfoCheck3:');
            System.debug(ppInfoCheck3);
        } catch (Exception ex) {
            // This will throw the Missing Student Fee exception message, if we need assertion and additional check this should be expanded
        }        

        Test.stopTest();
    }  
}