unpackaged/config/ready/StudentID/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>redu_Contact_Type__c</fullName>
        <label>Contact Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Applicant</fullName>
                </value>
                <value>
                    <fullName>Student</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

unpackaged/post/06_standard_object_tracking/objects/Contact.object
    <fields>
        <fullName>rio_ed__Student_ID__c</fullName>
        <inlineHelpText>This is the Student ID generated by this Institution for this Student</inlineHelpText>
        <label>Student ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>

unpackaged/post/02_heda_objects_ui/objects/hed__Trigger_Handler__c.object
<CustomObject>
    <description>Stores which classes to run in response to DML performed on an object.</description>
    <fields>
        <fullName>hed__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates that this module is active</description>
        <inlineHelpText>Indicates that this module is active</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>hed__Class__c</fullName>
        <description>Name of the class to be run</description>
        <inlineHelpText>Name of the class to be run</inlineHelpText>
        <label>Class</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>hed__Load_Order__c</fullName>
        <description>Order in which this module should be run, helps maintain dependencies in the modules and data.</description>
        <inlineHelpText>Order in which this module should be run, helps maintain dependencies in the modules and data.</inlineHelpText>
        <label>Load Order</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>hed__Object__c</fullName>
        <description>Name of the object this handler should be run for</description>
        <inlineHelpText>Name of the object this handler should be run for</inlineHelpText>
        <label>Object</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>hed__Trigger_Action__c</fullName>
        <description>Trigger Action in which this module should fire</description>
        <inlineHelpText>Trigger Action in which this module should fire</inlineHelpText>
        <label>Trigger Action</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BeforeInsert</fullName>
                </value>
                <value>
                    <fullName>BeforeUpdate</fullName>
                </value>
                <value>
                    <fullName>BeforeDelete</fullName>
                </value>
                <value>
                    <fullName>AfterInsert</fullName>
                </value>
                <value>
                    <fullName>AfterUpdate</fullName>
                </value>
                <value>
                    <fullName>AfterDelete</fullName>
                </value>
                <value>
                    <fullName>AfterUndelete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Trigger Handler</label>
    <nameField>
        <label>Trigger Handler Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trigger Handlers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/config/ready/11_StudentID/objects/redu_Student_Number__c.object
<CustomObject>
    <fields>
        <fullName>redu_Salesforce_Record_Id__c</fullName>
        <label>Salesforce Record Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>redu_Student_Email__c</fullName>
        <label>Student Email</label>
        <type>Email</type>
    </fields>
    <label>Student Number</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Student No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/config/ready/StudentID/classes/redu_CON_StudentID_TDTM.cls
/**
* @author           WDCi(LKoh)
* @date             Dec 2021
* @group            Contact Custom Automation
* @description      Automation to generate student number
* @change-history   15-12-2021 - Initial Build, Custom Automation for generating student number in Contact
*/
global without sharing class redu_CON_StudentID_TDTM extends hed.TDTM_Runnable {
    
    private static final String TYPE_STUDENT = 'Student';

    public class REPT_Exception extends Exception{}
    
    public override DmlWrapper run(List<SObject> newList, List<SObject> oldList, hed.TDTM_Runnable.Action triggerAction, Schema.DescribeSObjectResult objResult) {

        List<Contact> newContactList = (List<Contact>) newList;
        List<Contact> oldContactList = (List<Contact>) oldList;
        
        hed.TDTM_Runnable.dmlWrapper dmlWrapper = new hed.TDTM_Runnable.DmlWrapper();

        List<redu_Student_Number__c> studentNumberList = new List<redu_Student_Number__c>();
        
        if (triggerAction == hed.TDTM_Runnable.Action.AfterInsert || triggerAction == hed.TDTM_Runnable.Action.BeforeUpdate) {
            for (Contact con : newContactList) {
                if (String.isBlank(con.rio_ed__Student_ID__c) && con.redu_Contact_Type__c == TYPE_STUDENT) {
                    redu_Student_Number__c newStudentNumber = new redu_Student_Number__c();
                    newStudentNumber.redu_Salesforce_Record_Id__c = con.Id;
                    newStudentNumber.redu_Student_Email__c = con.Email;
                    studentNumberList.add(newStudentNumber);
                }
            }
        }        

        if (!studentNumberList.isEmpty()) {
            try {
                insert studentNumberList;

                List<redu_Student_Number__c> refreshedStudentNumberList = [SELECT Id, Name, redu_Salesforce_Record_Id__c FROM redu_Student_Number__c WHERE Id IN :studentNumberList];
                Map<Id, String> contactToStudentNumberMap = new Map<Id, String>();
                for (redu_Student_Number__c studentNum : refreshedStudentNumberList) {
                    contactToStudentNumberMap.put(studentNum.redu_Salesforce_Record_Id__c, studentNum.Name);
                }

                List<Contact> contactUpdateList = new List<Contact>();
                for (SObject contactSObj : newList) {
                    Contact currentContact = (Contact) contactSObj;

                    if (contactToStudentNumberMap.containsKey(currentContact.Id)) {
                        if (triggerAction == hed.TDTM_Runnable.Action.BeforeUpdate) {
                            currentContact.rio_ed__Student_ID__c = contactToStudentNumberMap.get(currentContact.Id);
                        } else {
                            Contact contactToUpdate = new Contact();
                            contactToUpdate.Id = currentContact.Id;
                            contactToUpdate.rio_ed__Student_ID__c = contactToStudentNumberMap.get(currentContact.Id);
                            contactUpdateList.add(contactToUpdate);
                        }
                    }
                }
                
                if (!contactUpdateList.isEmpty()) {
                    update contactUpdateList;
                }                
            } catch (Exception exp) {
                throw new REPT_Exception('Error encountered during Update Contact Student Number Automation. Error: Line ' + exp.getLineNumber() + ' - ' + exp.getMessage() );
            }
        }
        return dmlWrapper;
    }

    //────────────────────────────────────────────────────┐
    // TDTM Setting Installer
    //────────────────────────────────────────────────────┘
    public static void installTDTMSetting() {
        List<hed__Trigger_Handler__c> currentTriggerHandlerList = 
            [SELECT Id, hed__Active__c, rio_ed__Unique_Key__c, hed__Object__c, hed__Load_Order__c, hed__Trigger_Action__c, hed__Class__c
                FROM hed__Trigger_Handler__c 
                WHERE hed__Active__c = true AND rio_ed__Unique_Key__c = 'Contact_redu_CON_StudentID_TDTM_6'];
        if (currentTriggerHandlerList.isEmpty()) {
            hed__Trigger_Handler__c newTriggerHandler = new hed__Trigger_Handler__c(
                hed__Object__c = 'Contact',
                hed__Load_Order__c = 6,
                hed__Trigger_Action__c = 'BeforeUpdate;AfterInsert',
                hed__Class__c = 'redu_CON_StudentID_TDTM',
                hed__Active__c = true,
                rio_ed__Unique_Key__c = 'Contact_redu_CON_StudentID_TDTM_6'
            );
            insert newTriggerHandler;
        }
    }
}