unpackaged/config/ready/15_Calls/objects/hed__Course__c.object
<CustomObject>
</CustomObject>

unpackaged/post/02_heda_objects_ui/objects/hed__Course__c.object
    <fields>
        <fullName>hed__Account__c</fullName>
        <label>Department</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Courses</relationshipLabel>
        <relationshipName>Courses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>

unpackaged/config/ready/15_Calls/objects/hed__Course_Enrollment__c.object
<CustomObject>
</CustomObject>

unpackaged/post/07_heda_object_tracking/objects/hed__Course_Enrollment__c.object
    <fields>
        <fullName>hed__Course_Offering__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Course Offering the student or faculty member is involved with.</description>
        <inlineHelpText>The Course Offering the student or faculty member is involved with.</inlineHelpText>
        <label>Course Offering ID</label>
        <referenceTo>hed__Course_Offering__c</referenceTo>
        <relationshipLabel>Course Connection</relationshipLabel>
        <relationshipName>Course_Enrollment</relationshipName>
        <type>Lookup</type>
    </fields>

unpackaged/post/07_heda_object_tracking/objects/hed__Course_Enrollment__c.object
    <fields>
        <fullName>hed__Status__c</fullName>
        <description>Indicates whether this is a current or former Course Connection.</description>
        <inlineHelpText>Indicates whether this is a current or former Course Connection.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Current</fullName>
                    <default>true</default>
                    <label>Current</label>
                </value>
                <value>
                    <fullName>Former</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Enrolled</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Withdrew</fullName>
                </value>
                <value>
                    <fullName>Audit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/unpackaged/upgrade - v2.3/01_layouts_and_configs/objects/hed__Course_Enrollment__c.object
    <recordTypes>
        <fullName>Student</fullName>
        <active>true</active>
        <description>A Student Course Connection</description>
        <label>Student</label>
        
		
    </recordTypes>

unpackaged/post/07_heda_object_tracking/objects/hed__Course_Offering__c.object
<CustomObject>
    <description>Joins Courses and Terms to contain information related to a single occurrence of a Course.</description>
	<label>Course Offering</label>
    <nameField>
        <label>Course Offering ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Offerings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
	<fields>
        <fullName>hed__Term__c</fullName>
        <description>Lookup to the Term record that represents when this Course Offering takes place.</description>
        <label>Term</label>
        <referenceTo>hed__Term__c</referenceTo>
        <relationshipLabel>Course Offerings</relationshipLabel>
        <relationshipName>Course_Offerings</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>hed__End_Date__c</fullName>
        <description>The date of the last session for this Course Offering.</description>
        <inlineHelpText>The date of the last session for this Course Offering.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>hed__Start_Date__c</fullName>
        <description>The date of the first session for this Course Offering.</description>
        <inlineHelpText>The date of the first session for this Course Offering.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>rio_ed__Fee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Will be automatically set based on Fee Label and Course &quot;use default fee&quot; settings</inlineHelpText>
        <label>Fee</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>Only a Fee that has a Fee Unit of Course or Credit can be added to a Course record.</errorMessage>
            <filterItems>
                <field>rio_ed__Fee__c.rio_ed__Fee_Unit__c</field>
                <operation>equals</operation>
                <value>Course</value>
            </filterItems>
            <filterItems>
                <field>rio_ed__Fee__c.rio_ed__Fee_Unit__c</field>
                <operation>equals</operation>
                <value>Credit</value>
            </filterItems>
            <infoMessage>Please select a Fee for this Course.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>rio_ed__Fee__c</referenceTo>
        <relationshipLabel>Course Offerings</relationshipLabel>
        <relationshipName>Course_Offerings</relationshipName>
        <type>Lookup</type>
    </fields>
	
</CustomObject>

unpackaged/post/02_heda_objects_ui/objects/hed__Course_Offering__c.object
    <fields>
        <fullName>hed__Course__c</fullName>
        <label>Course</label>
        <referenceTo>hed__Course__c</referenceTo>
        <relationshipLabel>Course Offerings</relationshipLabel>
        <relationshipName>Course_Offerings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>

unpackaged/config/ready/18_HousingFeeGeneration/objects/hed__Program_Enrollment__c.object
<CustomObject>
</CustomObject>

unpackaged/post/07_heda_object_tracking/objects/hed__Program_Enrollment__c.object
    <fields>
        <fullName>hed__End_Date__c</fullName>
        <description>The date the student is scheduled to complete the Program.</description>
        <inlineHelpText>The date the student is scheduled to complete the Program.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>

unpackaged/post/07_heda_object_tracking/objects/hed__Program_Enrollment__c.object
    <fields>
        <fullName>hed__Start_Date__c</fullName>
        <description>The date the student started, or is expected to start, this Program.</description>
        <inlineHelpText>The date the student started, or is expected to start, this Program.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>

unpackaged/config/ready/StudentRequest/objects/hed__Program_Plan__c.object
<CustomObject>

</CustomObject>

unpackaged/post/02_heda_objects_ui/objects/hed__Term__c.object
<CustomObject>
    <description>Unit of time in which academic activities are taking place.</description>
    
    <fields>
        <fullName>hed__Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Terms</relationshipLabel>
        <relationshipName>Terms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    
    <label>Term</label>
    <nameField>
        <label>Term Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    
</CustomObject>

unpackaged/config/upgrade/upgrade - v2.11/02_custompicklist/objects/rio_ed__Fee__c.object
<CustomObject>
</CustomObject>

unpackaged/config/ready/03_FeeLine/objects/rio_ed__Fee_Line__c.object
<CustomObject>
</CustomObject>

unpackaged/config/ready/03_FeeLine/objects/rio_ed__Fee_Schedule__c.object
<CustomObject>
</CustomObject>

unpackaged/config/ready/18_HousingFeeGeneration/objects/rio_ed__PE_Pathway_Status__c.object
<CustomObject>
</CustomObject>

unpackaged/post/08_redu_object_tracking/objects/rio_ed__PE_Pathway_Status__c.object
	<fields>
        <fullName>rio_ed__Program_Enrollment__c</fullName>
        <label>Program Enrollment</label>
        <referenceTo>hed__Program_Enrollment__c</referenceTo>
        <relationshipLabel>PE Pathways</relationshipLabel>
        <relationshipName>PE_Pathway_Statuses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>

unpackaged/config/ready/Payment2us/objects/rio_ed__Student_Fee__c.object
<CustomObject>
</CustomObject>

unpackaged/config/ready/32_RIO_Education_AI/classes/REDU_AI_AddStudentFee_TEST.cls
/**
* @author           WDCi (LKoh)
* @date             May 2025
* @group            RIO Education (AgentForce)
* @description      Test Class for REDU_AI_AddStudentFee
* @change-history
*/
@isTest
private class REDU_AI_AddStudentFee_TEST {

    // Generate test data using REDU_AI_TestDataFactory
    @testSetup
    static void setupData() {

        List<hed.TDTM_Global_API.TdtmToken> tokens = hed.TDTM_Global_API.getTdtmConfig();

        // Create Settings for RIO Education
        REDU_AI_TestDataFactory_UTIL.createDefaultSettings();

        //Create our trigger handlers
        REDU_AI_TestDataFactory_UTIL.createRIOEdTriggerHandlers();

        // Pass trigger handler config to set method for this test run
        hed.TDTM_Global_API.setTdtmConfig(tokens);

        //Create Educational Institution Account
        Id eiRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Educational Institution').getRecordTypeId();

        Account educationalInstitution = new Account(
            Name = 'EducationalInstitution',
            rio_ed__EFTSL_Credit_Points__c = 100,
            RecordTypeId = eiRecordTypeId
        );

        insert educationalInstitution;

        //Create department account
        Id udRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('University Department').getRecordTypeId();
        Account universityDepartment = new Account(Name = 'UniversityDepartment',
                    ParentId = educationalInstitution.Id,
                    rio_ed__EFTSL_Credit_Points__c = 100,
                    RecordTypeId = udRecordTypeId);
        insert universityDepartment;

        //Create academic program account
        Id apRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Academic Program').getRecordTypeId();
        Account academicProgram = new Account(Name = 'AcademicProgram',
                    ParentId = universityDepartment.Id,
                    rio_ed__EFTSL_Credit_Points__c = 100,
                    rio_ed__Program_Code__c = 'AP',
                    rio_ed__Fee_Due_Days__c = 60,
                    RecordTypeId = apRecordTypeId);

        insert academicProgram;

        //Create program plan
        hed__Program_Plan__c pp = new hed__Program_Plan__c();
        pp.Name = 'Program Plan';
        pp.hed__Account__c = academicProgram.Id;
        pp.hed__Start_Date__c = System.today().addDays(-30);
        pp.hed__End_Date__c = System.today().addDays(30);
        pp.hed__Is_Primary__c = true;
        pp.hed__Status__c = 'Current';
        pp.rio_ed__Fee_Method__c = 'Term';
        insert pp;

        // Create another Program and Program Plan
        Account newAcademicProgram = new Account(Name = 'NewAcademicProgram',
                    ParentId = universityDepartment.Id,
                    rio_ed__EFTSL_Credit_Points__c = 100,
                    rio_ed__Program_Code__c = 'NAP',
                    rio_ed__Fee_Due_Days__c = 60,
                    RecordTypeId = apRecordTypeId);
        insert newAcademicProgram;

        hed__Program_Plan__c newPP = new hed__Program_Plan__c();
        newPP.Name = 'New Program Plan';
        newPP.hed__Account__c = newAcademicProgram.Id;
        newPP.hed__Start_Date__c = System.today().addDays(-30);
        newPP.hed__End_Date__c = System.today().addDays(30);
        newPP.hed__Is_Primary__c = true;
        newPP.hed__Status__c = 'Current';
        newPP.rio_ed__Fee_Method__c = 'Term';
        insert newPP;

        //Create contact for course enrollment
        Contact con = new Contact(
            LastName = 'Doe'
        );

        insert con;

        //Create term
        hed__Term__c term = new hed__Term__c(
            hed__Account__c = educationalInstitution.Id
        );

        insert term;

        //Create course
        hed__Course__c course = new hed__Course__c(
            Name = 'Test Course',
            hed__Course_ID__c = 'Test Course',
            hed__Account__c = educationalInstitution.Id
        );

        insert course;

        //Create course offering
        hed__Course_Offering__c co = new hed__Course_Offering__c(
            Name = 'Test CO',
            hed__Course__c = course.Id,
            hed__Term__c = term.Id
        );

        insert co;

        hed__Program_Enrollment__c pe = new hed__Program_Enrollment__c();
        pe.hed__Account__c = academicProgram.Id;
        pe.hed__Contact__c = con.Id;
        pe.hed__Program_Plan__c = pp.Id;
        pe.rio_ed__Fee_Method__c = 'Term';
        pe.rio_ed__Pay_Upfront__c = 'No';

        insert pe;

        // Create PE Pathway
        rio_ed__PE_Pathway_Status__c pathway = new rio_ed__PE_Pathway_Status__c();
        pathway.rio_ed__Program_Enrollment__c = pe.Id;
        pathway.rio_ed__Term__c = term.Id;
        insert pathway;

        // Create course enrollment
        hed__Course_Enrollment__c ce = new hed__Course_Enrollment__c();
        ce.hed__Program_Enrollment__c = pe.Id;
        ce.hed__Contact__c = pe.hed__Contact__c;
        ce.hed__Course_Offering__c = co.Id;

        insert ce;

        // Create Fee record
        rio_ed__Fee__c fee = new rio_ed__Fee__c();
        fee.Name = 'Test Fee';
        insert fee;

        // Create Fee Schedule
        rio_ed__Fee_Schedule__c fs = new rio_ed__Fee_Schedule__c();
        fs.rio_ed__Fee__c = fee.Id;
        fs.rio_ed__Fee_Amount_Domestic__c = 1000;
        fs.rio_ed__Fee_Amount_International__c = 2000;
        insert fs;

        // Create Fee Schedule Term
        rio_ed__Fee_Schedule_Term__c fst = new rio_ed__Fee_Schedule_Term__c();
        fst.rio_ed__Fee_Schedule__c = fs.Id;
        fst.rio_ed__Term__c = term.Id;
        insert fst;

        // Create Student Fee record
        rio_ed__Student_Fee__c sf = new rio_ed__Student_Fee__c();
        sf.rio_ed__Program_Enrollment__c = pe.Id;
        sf.rio_ed__PE_Pathway__c = pathway.Id;
        insert sf;

        // Create Fee Line
        rio_ed__Fee_Line__c fl = new rio_ed__Fee_Line__c();
        fl.rio_ed__Student_Fee__c = sf.Id;
        fl.rio_ed__Course_Connection__c = ce.Id;
        insert fl;
    }

    @isTest
    static void testAddExistingStudentFee() {
        // Create a request for the test
        REDU_AI_AddStudentFee.Request req = new REDU_AI_AddStudentFee.Request();
        req.contactId = [SELECT Id FROM Contact LIMIT 1].Id;
        req.termId = [SELECT Id FROM hed__Term__c LIMIT 1].Id;
        req.feeId = [SELECT Id FROM rio_ed__Fee__c LIMIT 1].Id;

        List<REDU_AI_AddStudentFee.Request> requests = new List<REDU_AI_AddStudentFee.Request>();
        // Add the request to the list
        requests.add(req);

        // Call the method to test
        List<REDU_AI_InvocableResponse> responses = REDU_AI_AddStudentFee.addStudentFee(requests);

        // Verify the response
        Assert.isNotNull(responses, 'The response should not be null.');
        Assert.isTrue(responses.size() > 0, 'There should be at least one response.');

        for (REDU_AI_InvocableResponse response : responses) {
            Assert.isTrue(response.isSuccess == true, 'The response should be successful.');
        }

        // Verify that the Student Fee record was created
        List<rio_ed__Student_Fee__c> studentFees = [SELECT Id FROM rio_ed__Student_Fee__c WHERE rio_ed__Program_Enrollment__c IN (SELECT Id FROM hed__Program_Enrollment__c WHERE hed__Contact__c = :req.contactId)];
        Assert.isTrue(studentFees.size() > 0, 'The Student Fee record should be created.');
    }

    @isTest
    static void testAddNewStudentFee() {

        // To simulate the condition for this, we will remove the existing Student Fee record from the test data
        List<rio_ed__Student_Fee__c> existingFees = [SELECT Id FROM rio_ed__Student_Fee__c];
        if (!existingFees.isEmpty()) {
            delete existingFees;
        }
        // Create a request for the test
        REDU_AI_AddStudentFee.Request req = new REDU_AI_AddStudentFee.Request();
        req.contactId = [SELECT Id FROM Contact LIMIT 1].Id;
        req.termId = [SELECT Id FROM hed__Term__c LIMIT 1].Id;
        req.feeId = [SELECT Id FROM rio_ed__Fee__c LIMIT 1].Id;

        List<REDU_AI_AddStudentFee.Request> requests = new List<REDU_AI_AddStudentFee.Request>();
        // Add the request to the list
        requests.add(req);
        // Call the method to test
        List<REDU_AI_InvocableResponse> responses = REDU_AI_AddStudentFee.addStudentFee(requests);
        // Verify the response
        Assert.isNotNull(responses, 'The response should not be null.');
        Assert.isTrue(responses.size() > 0, 'There should be at least one response.');
        for (REDU_AI_InvocableResponse response : responses) {
            Assert.isTrue(response.isSuccess == true, 'The response should be successful.');
        }
        // Verify that the Student Fee record was created
        List<rio_ed__Student_Fee__c> studentFees = [SELECT Id FROM rio_ed__Student_Fee__c WHERE rio_ed__Program_Enrollment__c IN (SELECT Id FROM hed__Program_Enrollment__c WHERE hed__Contact__c = :req.contactId)];
        Assert.isTrue(studentFees.size() > 0, 'The Student Fee record should be created.');
    }
}