unpackaged/config/ready/15_Calls/objects/hed__Course__c.object
<CustomObject>
</CustomObject>

unpackaged/config/ready/15_Calls/objects/hed__Course_Enrollment__c.object
<CustomObject>
    <fields>
        <fullName>REDU_Grade_Override__c</fullName>
        <label>Grade Override</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No Show</fullName>
                </value>
                <value>
                    <fullName>Postponed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>REDU_Grade_Type__c</fullName>
        <label>Grade Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>rio_ed__Grading_Period_Types</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

unpackaged/post/07_heda_object_tracking/objects/hed__Course_Enrollment__c.object
    <fields>
        <fullName>hed__Course_Offering__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Course Offering the student or faculty member is involved with.</description>
        <inlineHelpText>The Course Offering the student or faculty member is involved with.</inlineHelpText>
        <label>Course Offering ID</label>
        <referenceTo>hed__Course_Offering__c</referenceTo>
        <relationshipLabel>Course Connection</relationshipLabel>
        <relationshipName>Course_Enrollment</relationshipName>
        <type>Lookup</type>
    </fields>

unpackaged/post/07_heda_object_tracking/objects/hed__Course_Enrollment__c.object
    <fields>
        <fullName>hed__Grade__c</fullName>
        <description>The numeric grade the student earned in this Course Offering.</description>
        <inlineHelpText>The numeric grade the student earned in this Course Offering.</inlineHelpText>
        <label>Grade</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>

unpackaged/post/07_heda_object_tracking/objects/hed__Course_Enrollment__c.object
    <fields>
        <fullName>hed__Status__c</fullName>
        <description>Indicates whether this is a current or former Course Connection.</description>
        <inlineHelpText>Indicates whether this is a current or former Course Connection.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Current</fullName>
                    <default>true</default>
                    <label>Current</label>
                </value>
                <value>
                    <fullName>Former</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Enrolled</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Withdrew</fullName>
                </value>
                <value>
                    <fullName>Audit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

unpackaged/post/07_heda_object_tracking/objects/hed__Course_Enrollment__c.object
    <fields>
        <fullName>rio_ed__Release_Grades__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Used to release grades to students and trigger the completion engine</inlineHelpText>
        <label>Release Grades</label>
        <type>Checkbox</type>
    </fields>

unpackaged/post/07_heda_object_tracking/objects/hed__Course_Offering__c.object
<CustomObject>
    <description>Joins Courses and Terms to contain information related to a single occurrence of a Course.</description>
	<label>Course Offering</label>
    <nameField>
        <label>Course Offering ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Offerings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>rio_ed__Release_Grades__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field's functionality has been replaced with the Grade Release Wizard.</description>
        <inlineHelpText>This field's functionality has been replaced with the Grade Release Wizard.</inlineHelpText>
        <label>(Obsolete) Release Grades</label>
        <type>Checkbox</type>
    </fields>
	
</CustomObject>

unpackaged/post/02_heda_objects_ui/objects/hed__Course_Offering__c.object
    <fields>
        <fullName>hed__Course__c</fullName>
        <label>Course</label>
        <referenceTo>hed__Course__c</referenceTo>
        <relationshipLabel>Course Offerings</relationshipLabel>
        <relationshipName>Course_Offerings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>

unpackaged/config/ready/15_Calls/objects/hed__Term_Grade__c.object
<CustomObject>
    <fields>
        <fullName>REDU_Call_Override__c</fullName>
        <label>Call Override</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>rio_ed__Grading_Period_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>REDU_Grade_Override__c</fullName>
        <label>Grade Override</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No Show</fullName>
                </value>
                <value>
                    <fullName>Postponed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

unpackaged/post/02_heda_objects_ui/objects/hed__Trigger_Handler__c.object
<CustomObject>
    <description>Stores which classes to run in response to DML performed on an object.</description>
    <fields>
        <fullName>hed__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates that this module is active</description>
        <inlineHelpText>Indicates that this module is active</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>hed__Class__c</fullName>
        <description>Name of the class to be run</description>
        <inlineHelpText>Name of the class to be run</inlineHelpText>
        <label>Class</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>hed__Load_Order__c</fullName>
        <description>Order in which this module should be run, helps maintain dependencies in the modules and data.</description>
        <inlineHelpText>Order in which this module should be run, helps maintain dependencies in the modules and data.</inlineHelpText>
        <label>Load Order</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>hed__Object__c</fullName>
        <description>Name of the object this handler should be run for</description>
        <inlineHelpText>Name of the object this handler should be run for</inlineHelpText>
        <label>Object</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>hed__Trigger_Action__c</fullName>
        <description>Trigger Action in which this module should fire</description>
        <inlineHelpText>Trigger Action in which this module should fire</inlineHelpText>
        <label>Trigger Action</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BeforeInsert</fullName>
                </value>
                <value>
                    <fullName>BeforeUpdate</fullName>
                </value>
                <value>
                    <fullName>BeforeDelete</fullName>
                </value>
                <value>
                    <fullName>AfterInsert</fullName>
                </value>
                <value>
                    <fullName>AfterUpdate</fullName>
                </value>
                <value>
                    <fullName>AfterDelete</fullName>
                </value>
                <value>
                    <fullName>AfterUndelete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>hed__User_Managed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The record is managed by the user and updates won&apos;t be pushed to it.</description>
        <inlineHelpText>Check it if you intent to manage the record yourself. Be aware that updates to the package won&apos;t update the record.</inlineHelpText>
        <label>User Managed</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger Handler</label>
    <nameField>
        <label>Trigger Handler Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trigger Handlers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/config/ready/15_Calls/objects/rio_ed__Grade__c.object
<CustomObject>
    <fields>
        <fullName>REDU_Call_Override__c</fullName>
        <label>Call Override</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>rio_ed__Grading_Period_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>REDU_Grade_Override__c</fullName>
        <label>Grade Override</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No Show</fullName>
                </value>
                <value>
                    <fullName>Postponed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

unpackaged/config/ready/15_Calls/globalValueSets/rio_ed__Grading_Period_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Mid-Term Grade</fullName>
    </customValue>
    <customValue>
        <fullName>Final Grade</fullName>
        <default>true</default>
        <label>Final Grade</label>
    </customValue>
    <customValue>
        <fullName>Grading Period</fullName>
    </customValue>
    <customValue>
        <fullName>Ordinary</fullName>
    </customValue>
    <customValue>
        <fullName>Extraordinary</fullName>
    </customValue>
    <description>Grading period type, similar to the Term Grade Type on term grade.</description>
    <masterLabel>Grading Period Types</masterLabel>
</GlobalValueSet>

unpackaged/config/ready/15_Calls/classes/redu_GRD_GradeToTermGradeRollup_TDTM.cls
/**
 * @Author     WDCi (Vin)
 * @Date     Mar 2021
 * @group     Grade
 * @Description To rollup the sum of “Weighted Points” from grade to term grade
 *
 * @changehistory
 * ISS-001328 09/09/2022 Jordan - Added calls functionality for Calls RIO Ready component
 */

global without sharing class redu_GRD_GradeToTermGradeRollup_TDTM extends hed.TDTM_Runnable {

    Id gradeRT = Schema.SObjectType.rio_ed__Grade__c.getRecordTypeInfosByName().get('Grade').getRecordTypeId();

    /**
     * @description Trigger Handler on rio_ed__Grade__c
     * @param newList the list of rio_ed__Grade__c from trigger new
     * @param oldList the list of rio_ed__Grade__c from trigger old
     * @param triggerAction which trigger event (BeforeInsert, AfterInsert, etc.).
     * @param objResult the describe for rio_ed__Grade__c
     * @return DmlWrapper
     */
    public override DmlWrapper run(List<SObject> newList, List<SObject> oldList, hed.TDTM_Runnable.Action triggerAction, Schema.DescribeSObjectResult objResult) {
        hed.TDTM_Runnable.DmlWrapper dmlWrapper = null;

        List<rio_ed__Grade__c> newGrade = (List<rio_ed__Grade__c>) newList;
        List<rio_ed__Grade__c> oldGrade = (List<rio_ed__Grade__c>) oldList;

        Set<Id> termGradeIdsUpdateGrades = new Set<Id>();
        Set<Id> gradeIdsSetOverrides = new Set<Id>();
        Set<Id> termGradeIdsSetOverrides = new Set<Id>();
        Set<Id> termGradeIdsClearOverrides = new Set<Id>();

        //Get qualified grade
        if (triggerAction == hed.TDTM_Runnable.Action.AfterInsert) {
            for (rio_ed__Grade__c grade : newGrade) {
                if (grade.RecordTypeId == gradeRT && grade.rio_ed__Term_Grade__c <> null) {
                    if (grade.rio_ed__Weighted_Points__c <> null || grade.rio_ed__Grade_Value__c <> null) {
                        termGradeIdsUpdateGrades.add(grade.rio_ed__Term_Grade__c);
                    }

                    if (grade.REDU_Grade_Override__c <> null || grade.REDU_Call_Override__c <> null) {
                        gradeIdsSetOverrides.add(grade.Id);
                        termGradeIdsSetOverrides.add(grade.rio_ed__Term_Grade__c);
                    }
                }
            }
        } else if (triggerAction == hed.TDTM_Runnable.Action.AfterUpdate) {
            for (Integer i = 0; i < newGrade.size(); i++) {
                if (newGrade[i].RecordTypeId == gradeRT && newGrade[i].rio_ed__Term_Grade__c <> null) {
                    if (
                        newGrade[i].rio_ed__Weighted_Points__c <> oldGrade[i].rio_ed__Weighted_Points__c
                        || newGrade[i].rio_ed__Grade_Value__c <> oldGrade[i].rio_ed__Grade_Value__c
                    ) {
                        termGradeIdsUpdateGrades.add(newGrade[i].rio_ed__Term_Grade__c);
                    }

                    if (
                        newGrade[i].REDU_Grade_Override__c <> oldGrade[i].REDU_Grade_Override__c || 
                        newGrade[i].REDU_Call_Override__c <> oldGrade[i].REDU_Call_Override__c) 
                    {
                        gradeIdsSetOverrides.add(newGrade[i].Id);
                        termGradeIdsSetOverrides.add(newGrade[i].rio_ed__Term_Grade__c);
                    }
                }
            }
        } else if (triggerAction == hed.TDTM_Runnable.Action.AfterDelete) {
            for (rio_ed__Grade__c grade : oldGrade) {
                if (grade.RecordTypeId == gradeRT && grade.rio_ed__Term_Grade__c <> null) {
                    if (grade.rio_ed__Weighted_Points__c <> null || grade.rio_ed__Grade_Value__c <> null) {
                        termGradeIdsUpdateGrades.add(grade.rio_ed__Term_Grade__c);
                    }

                    if (grade.REDU_Grade_Override__c <> null || grade.REDU_Call_Override__c <> null) {
                        termGradeIdsClearOverrides.add(grade.rio_ed__Term_Grade__c);
                    }
                }
            }
        }

        //Get all grade related to the qualified term grade
        if (!termGradeIdsUpdateGrades.isEmpty() || !termGradeIdsSetOverrides.isEmpty() || !termGradeIdsClearOverrides.isEmpty()) {
            Map<Id, hed__Term_Grade__c> updateTermGrades = new Map<Id, hed__Term_Grade__c>([
                SELECT 
                    hed__Course_Connection__c,
                    hed__Letter_Grade__c, 
                    hed__Numerical_Grade__c, 
                    hed__Term_Grade_Type__c, 
                    REDU_Call_Override__c, 
                    REDU_Grade_Override__c, 
                    hed__Course_Connection__r.hed__Course_Offering__r.hed__Course__r.rio_ed__Grade_Type__c
                FROM hed__Term_Grade__c
                WHERE (Id IN :termGradeIdsUpdateGrades OR Id IN :termGradeIdsSetOverrides)
            ]);
            
            List<rio_ed__Grade__c> gradeList = [
                SELECT 
                    Id, 
                    rio_ed__Weighted_Points__c, 
                    rio_ed__Term_Grade__c, 
                    rio_ed__Weight__c,
                    rio_ed__Grade_Points__c, 
                    rio_ed__Grade_Value__c, 
                    REDU_Grade_Override__c, 
                    REDU_Call_Override__c,
                    rio_ed__Term_Grade__r.hed__Course_Connection__r.hed__Course_Offering__r.hed__Course__r.rio_ed__Grade_Setting_Type__c,
                    rio_ed__Term_Grade__r.hed__Course_Connection__r.hed__Course_Offering__r.hed__Course__r.hed__Account__r.ParentId,
                    rio_ed__Term_Grade__r.hed__Course_Connection__r.hed__Course_Offering__r.hed__Course__r.hed__Account__c,
                    rio_ed__Term_Grade__r.hed__Course_Connection__r.hed__Account__c
                FROM rio_ed__Grade__c
                WHERE rio_ed__Term_Grade__c IN :updateTermGrades.keySet()
                AND RecordTypeId = :gradeRT
            ];

            Map<Id, Decimal> totalChildGradeWeightByParent = new Map<Id, Decimal>();
            Set<Id> termGradeGradesUpdated = new Set<Id>();

            //Get grade settings
            Set<Id> gsAcctIds = new Set<Id>();

            for (rio_ed__Grade__c grade : gradeList) {
                if (grade.rio_ed__Term_Grade__r.hed__Course_Connection__r.hed__Course_Offering__r.hed__Course__r.rio_ed__Grade_Setting_Type__c == 'Educational Institution') {
                    if (String.isNotBlank(grade.rio_ed__Term_Grade__r.hed__Course_Connection__r.hed__Course_Offering__r.hed__Course__r.hed__Account__r.ParentId)) {
                        gsAcctIds.add(grade.rio_ed__Term_Grade__r.hed__Course_Connection__r.hed__Course_Offering__r.hed__Course__r.hed__Account__r.ParentId);
                    }
                } else if (grade.rio_ed__Term_Grade__r.hed__Course_Connection__r.hed__Course_Offering__r.hed__Course__r.rio_ed__Grade_Setting_Type__c == 'University Department') {
                    if (String.isNotBlank(grade.rio_ed__Term_Grade__r.hed__Course_Connection__r.hed__Course_Offering__r.hed__Course__r.hed__Account__c)) {
                        gsAcctIds.add(grade.rio_ed__Term_Grade__r.hed__Course_Connection__r.hed__Course_Offering__r.hed__Course__r.hed__Account__c);
                    }
                } else if (grade.rio_ed__Term_Grade__r.hed__Course_Connection__r.hed__Course_Offering__r.hed__Course__r.rio_ed__Grade_Setting_Type__c == 'Academic Program') {
                    if (String.isNotBlank(grade.rio_ed__Term_Grade__r.hed__Course_Connection__r.hed__Account__c)) {
                        gsAcctIds.add(grade.rio_ed__Term_Grade__r.hed__Course_Connection__r.hed__Account__c);
                    }
                }
            }

            List<REDU_GradesRollup_UTIL.GradeSettingWrapper> gradeSettings = REDU_GradesRollup_UTIL.getGradeSettings(gsAcctIds);

            for (rio_ed__Grade__c grade : gradeList) {
                //If only value is set, set grade points according to Grade Value Scoring Range
                if (String.isNotBlank(grade.rio_ed__Grade_Value__c) && grade.rio_ed__Grade_Points__c == null) {
                    for (REDU_GradesRollup_UTIL.GradeSettingWrapper gs : gradeSettings) {
                        if (gs.gradeValue == grade.rio_ed__Grade_Value__c) {
                            
                            if(String.isNotBlank(gs.gradeValueScoringRange)){
                                if(gs.gradeValueScoringRange == 'Lower Range'){
                                    grade.rio_ed__Grade_Points__c = gs.lowerRange;
                                } else {
                                    grade.rio_ed__Grade_Points__c = gs.higherRange;
                                }
                            }

                            break;
                        }
                    }
                }

                //Update numerical grade in term grade
                if (termGradeIdsUpdateGrades.contains(grade.rio_ed__Term_Grade__c)) {
                    Decimal weightedPoints = null;

                    if (grade.rio_ed__Weighted_Points__c != 0) {
                        weightedPoints = grade.rio_ed__Weighted_Points__c;
                    } else if (grade.rio_ed__Grade_Points__c != null) {
                        weightedPoints = (grade.rio_ed__Weight__c / 100) * grade.rio_ed__Grade_Points__c;
                    }

                    if (weightedPoints != null) {
                        if (termGradeGradesUpdated.contains(grade.rio_ed__Term_Grade__c)) {
                            updateTermGrades.get(grade.rio_ed__Term_Grade__c).hed__Numerical_Grade__c =
                                updateTermGrades.get(grade.rio_ed__Term_Grade__c).hed__Numerical_Grade__c + weightedPoints;

                            Decimal weight = totalChildGradeWeightByParent.get(grade.rio_ed__Term_Grade__c) + grade.rio_ed__Weight__c;
                            totalChildGradeWeightByParent.put(grade.rio_ed__Term_Grade__c, weight);
                        } else {
                            updateTermGrades.get(grade.rio_ed__Term_Grade__c).hed__Numerical_Grade__c = weightedPoints;

                            totalChildGradeWeightByParent.put(grade.rio_ed__Term_Grade__c, grade.rio_ed__Weight__c);
                            termGradeGradesUpdated.add(grade.rio_ed__Term_Grade__c);
                        }
                    }
                }

                //Update override fields
                if (termGradeIdsSetOverrides.contains(grade.rio_ed__Term_Grade__c) && gradeIdsSetOverrides.contains(grade.Id)) {
                    updateTermGrades.get(grade.rio_ed__Term_Grade__c).REDU_Call_Override__c = grade.REDU_Call_Override__c;
                    updateTermGrades.get(grade.rio_ed__Term_Grade__c).REDU_Grade_Override__c = grade.REDU_Grade_Override__c;
                }
            }

            //Set numerical grades
            for (Id tgId : termGradeIdsUpdateGrades) {
                if (!termGradeGradesUpdated.contains(tgId)) {
                    updateTermGrades.get(tgId).hed__Numerical_Grade__c = null;
                } else {
                    updateTermGrades.get(tgId).hed__Numerical_Grade__c = 
                    updateTermGrades.get(tgId).hed__Numerical_Grade__c / totalChildGradeWeightByParent.get(tgId) * 100;
                }
            }

            //Set letter grades
            for (Id tgId : termGradeIdsUpdateGrades) {
                if (!termGradeGradesUpdated.contains(tgId)) {
                    updateTermGrades.get(tgId).hed__Letter_Grade__c = null;
                } else {
                    Decimal numericalGrade = updateTermGrades.get(tgId).hed__Numerical_Grade__c;

                    for (REDU_GradesRollup_UTIL.GradeSettingWrapper gs : gradeSettings) {
                        if (numericalGrade != null) {
                            if (gs.lowerRange <= numericalGrade && numericalGrade <= gs.higherRange) {

                                updateTermGrades.get(tgId).hed__Letter_Grade__c = gs.gradeValue;
                                break;
                            }
                        }
                    }
                }
            }

            // Clear override fields for term grades with deleted grades
            List<hed__Term_Grade__c> termGradeListClearOverrides = [
                SELECT Id, REDU_Call_Override__c, REDU_Grade_Override__c
                FROM hed__Term_Grade__c
                WHERE Id IN :termGradeIdsClearOverrides
            ];

            for (hed__Term_Grade__c termGrade : termGradeListClearOverrides) {
                updateTermGrades.get(termGrade.Id).REDU_Call_Override__c = '';
                updateTermGrades.get(termGrade.Id).REDU_Grade_Override__c = '';
            }

            update updateTermGrades.values();

            //Get course connections related to qualified term grades
            Set<Id> ccIds = new Set<Id>();

            for (hed__Term_Grade__c termGrade : updateTermGrades.values()) {
                if (termGrade.hed__Course_Connection__c != null) {
                    ccIds.add(termGrade.hed__Course_Connection__c);
                }
            }

            Map<Id, hed__Course_Enrollment__c> updateCourseConnections = new Map<Id, hed__Course_Enrollment__c>([
                SELECT 
                    Id, 
                    hed__Grade__c, 
                    hed__Status__c, 
                    rio_ed__Grade_Result__c, 
                    rio_ed__Release_Grades__c, 
                    REDU_Grade_Override__c, 
                    REDU_Grade_Type__c, 
                    hed__Course_Offering__r.hed__Course__r.rio_ed__Grade_Type__c
                FROM hed__Course_Enrollment__c
                WHERE Id IN :ccIds
            ]);

            //Update fields in course connection
            for (hed__Term_Grade__c termGrade : updateTermGrades.values()) {
                if (updateCourseConnections.containsKey(termGrade.hed__Course_Connection__c)) {
                    hed__Course_Enrollment__c cc = updateCourseConnections.get(termGrade.hed__Course_Connection__c);

                    if (cc.hed__Status__c != 'Completed' && !cc.rio_ed__Release_Grades__c) {
                        cc.hed__Grade__c = termGrade.hed__Numerical_Grade__c;
                        cc.rio_ed__Grade_Value__c = termGrade.hed__Letter_Grade__c;

                        if (termGrade.hed__Numerical_Grade__c != null) {
                            for (REDU_GradesRollup_UTIL.GradeSettingWrapper gs : gradeSettings) {
                                if (gs.lowerRange <= termGrade.hed__Numerical_Grade__c && termGrade.hed__Numerical_Grade__c <= gs.higherRange) {
                                    cc.rio_ed__Grade_Points__c = gs.gradePoints;
                                    break;
                                }
                            }
                        } else {
                            cc.rio_ed__Grade_Points__c = null;
                        }

                        if (String.isNotBlank(termGrade.REDU_Call_Override__c)) {
                            cc.REDU_Grade_Type__c = termGrade.REDU_Call_Override__c;
                        } else {
                            cc.REDU_Grade_Type__c = termGrade.hed__Term_Grade_Type__c;
                        }

                        cc.REDU_Grade_Override__c = termGrade.REDU_Grade_Override__c;

                        if (termGrade.REDU_Grade_Override__c == 'No Show' && String.isNotBlank(cc.rio_ed__Grade_Result__c)) {
                            cc.rio_ed__Grade_Result__c = '';
                        }
                    }

                    updateCourseConnections.put(termGrade.hed__Course_Connection__c, cc);
                }
            }

            if (!updateCourseConnections.values().isEmpty()) {
                update updateCourseConnections.values();
            }
        }

        return dmlWrapper;
    }

    //────────────────────────────────────────────────────┐
    // TDTM Setting Installer
    //────────────────────────────────────────────────────┘
    public static void installTDTMSetting() {
        List<hed__Trigger_Handler__c> currentTriggerHandlerList = 
            [SELECT Id, hed__Active__c, rio_ed__Unique_Key__c, hed__Object__c, hed__Load_Order__c, hed__Trigger_Action__c, hed__Class__c
                FROM hed__Trigger_Handler__c 
                WHERE hed__Active__c = true AND rio_ed__Unique_Key__c = 'rio_ed__Grade__c_redu_GRD_GradeToTermGradeRollup_TDTM_1'];
        if (currentTriggerHandlerList.isEmpty()) {
            hed__Trigger_Handler__c newTriggerHandler = new hed__Trigger_Handler__c(
                Name = 'RIOREADY_GRD_GradeToTermGradeRollup',
                hed__Object__c = 'rio_ed__Grade__c',
                hed__Load_Order__c = 1,
                hed__Trigger_Action__c = 'AfterInsert;AfterUpdate;AfterDelete',
                hed__Class__c = 'redu_GRD_GradeToTermGradeRollup_TDTM',
                hed__Active__c = true,
                hed__User_Managed__c = true,
                rio_ed__Unique_Key__c = 'rio_ed__Grade__c_redu_GRD_GradeToTermGradeRollup_TDTM_1'
            );
            insert newTriggerHandler;
        }
    }
}