unpackaged/config/ready/19_Student_Ledger/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>redu_Student_Ledger__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student Ledger</label>
        <referenceTo>redu_Student_Ledger__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

unpackaged/config/ready/18_HousingFeeGeneration/objects/hed__Program_Enrollment__c.object
<CustomObject>
</CustomObject>

unpackaged/post/02_heda_objects_ui/objects/hed__Trigger_Handler__c.object
<CustomObject>
    <description>Stores which classes to run in response to DML performed on an object.</description>
    <fields>
        <fullName>hed__Class__c</fullName>
        <description>Name of the class to be run</description>
        <inlineHelpText>Name of the class to be run</inlineHelpText>
        <label>Class</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>hed__Load_Order__c</fullName>
        <description>Order in which this module should be run, helps maintain dependencies in the modules and data.</description>
        <inlineHelpText>Order in which this module should be run, helps maintain dependencies in the modules and data.</inlineHelpText>
        <label>Load Order</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Trigger Handler</label>
    <nameField>
        <label>Trigger Handler Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trigger Handlers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/config/ready/19_Student_Ledger/objects/redu_Ledger_Entry__c.object
<CustomObject>
    <fields>
        <fullName>redu_Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>redu_Payment_Amount__c</fullName>
        <label>Payment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>redu_Related_Payment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Payment</label>
        <referenceTo>rio_ed__Fee_Payment__c</referenceTo>
        <relationshipLabel>Ledger Entries</relationshipLabel>
        <relationshipName>Ledger_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>redu_Student_Ledger__c</fullName>
        <label>Student Ledger</label>
        <referenceTo>redu_Student_Ledger__c</referenceTo>
        <relationshipLabel>Ledger Entries</relationshipLabel>
        <relationshipName>Ledger_Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>redu_Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Fee</fullName>
                </value>
                <value>
                    <fullName>Payment</fullName>
                </value>
                <value>
                    <fullName>Scholarship</fullName>
                </value>
                <value>
                    <fullName>Sponsor</fullName>
                </value>
                <value>
                    <fullName>Discount</fullName>
                </value>
                <value>
                    <fullName>Discount %</fullName>
                </value>
                <value>
                    <fullName>Refund</fullName>
                </value>
                <value>
                    <fullName>Credit Note</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ledger Entry</label>
    <nameField>
        <displayFormat>LE-{000000}</displayFormat>
        <label>Ledger Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/config/ready/19_Student_Ledger/objects/redu_Student_Ledger__c.object
<CustomObject>
    <fields>
        <fullName>redu_Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Student Ledgers</relationshipLabel>
        <relationshipName>Student_Ledgers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Student Ledger</label>
    <nameField>
        <displayFormat>SL-{000000}</displayFormat>
        <label>Student Ledger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Ledgers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/config/ready/Payment2us/objects/rio_ed__Student_Fee__c.object
<CustomObject>
</CustomObject>

unpackaged/config/ready/19_Student_Ledger/classes/redu_PAYMENT_LedgerEntry_TEST.cls
/**
* @author           WDCi-LKoh (Original by: ???)
* @date             Oct 2020
* @group            Ledger Entry Automation for Payment
* @description      Test class for redu_PAYMENT_LedgerEntry_TDTM
* @change-history   
*/
@isTest
public class redu_PAYMENT_LedgerEntry_TEST {
    @isTest
    static void testCreatePayment() {
        // first retrieve default EDA trigger handlers
       	List<hed.TDTM_Global_API.TdtmToken> tokens = hed.TDTM_Global_API.getTdtmConfig();

       	// Create our trigger handler using the constructor
       	// tokens.add(new hed.TDTM_Global_API.TdtmToken('redu_SFEE_StudentLedger_TDTM', 'rio_ed__Student_Fee__c', 'AfterInsert', 1.00));
       	// tokens.add(new hed.TDTM_Global_API.TdtmToken('redu_PAYMENT_LedgerEntry_TDTM', 'rio_ed__Fee_Payment__c', 'AfterInsert;AfterUpdate;BeforeDelete', 1.00));

       	// Pass trigger handler config to set method for this test run
       	hed.TDTM_Global_API.setTdtmConfig(tokens);

        // Create our trigger handler
        redu_SFEE_StudentLedger_TDTM.installTDTMSetting();
        redu_PAYMENT_LedgerEntry_TDTM.installTDTMSetting();

        List<hed__Trigger_Handler__c> triggerHandlers = [
            SELECT Id, Name, hed__Class__c, hed__Load_Order__c	
            FROM hed__Trigger_Handler__c
            WHERE hed__Class__c = 'redu_PAYMENT_LedgerEntry_TDTM'
        ];

        for (hed__Trigger_Handler__c th : triggerHandlers) {
            System.debug(th);
        }

       	// setup our test data...
        Contact ct = new Contact(LastName='Test');
       	insert ct;
       	hed__Program_Enrollment__c pe = new hed__Program_Enrollment__c(hed__Contact__c=ct.Id);
       	insert pe;
        rio_ed__Student_Fee__c sf = new rio_ed__Student_Fee__c(rio_ed__Program_Enrollment__c=pe.Id);
       	insert sf;
        
        redu_Student_Ledger__c ledger = [
            SELECT Id 
            FROM redu_Student_Ledger__c 
            WHERE redu_Contact__c = :ct.Id
        ];

        //== DEBUG ==
        System.debug('ledger:');
        System.debug(ledger);

        List<redu_Student_Ledger__c> studentLedgers = [
            SELECT Id 
            FROM redu_Student_Ledger__c 
            WHERE redu_Contact__c = :ct.Id
        ];
        System.debug('studentLedgers:');
        System.debug(studentLedgers);
        //== END DEBUG ==

        List<redu_Ledger_Entry__c> before = [
            SELECT Id 
            FROM redu_Ledger_Entry__c 
            WHERE redu_Student_Ledger__c = :ledger.Id
        ];
        
        test.startTest();

        //== DEBUG
        List<rio_ed__Fee_Payment__c> paymentCheck1 = [
            SELECT rio_ed__Payment_Amount__c, rio_ed__Payment_Date__c, rio_ed__Transaction_Type__c 
            FROM rio_ed__Fee_Payment__c        
        ];
        for (rio_ed__Fee_Payment__c fp : paymentCheck1) {
            System.debug(fp);
        }
        System.debug(paymentCheck1.size());
        //== END DEBUG

       	// do some operations...
        rio_ed__Fee_Payment__c paymentToInsert = new rio_ed__Fee_Payment__c(
            rio_ed__Student_Fee__c          = sf.Id, 
            rio_ed__Payment_Amount__c       = 500,
            rio_ed__Payment_Date__c         = Date.today(), 
            rio_ed__Transaction_Type__c     = 'Refund'
        );
        
        System.debug(paymentToInsert);
        insert paymentToInsert;
        
        rio_ed__Fee_Payment__c payment = [
            SELECT rio_ed__Payment_Amount__c, rio_ed__Payment_Date__c, rio_ed__Transaction_Type__c 
            FROM rio_ed__Fee_Payment__c        
        ];

        //== DEBUG        
        System.debug(payment);
        //== END DEBUG

        test.stopTest();
       	// validate our results...
       	List<redu_Ledger_Entry__c> after = [
            SELECT redu_Payment_Amount__c, redu_Date__c, redu_Related_Payment__c, redu_Type__c 
            FROM redu_Ledger_Entry__c 
            WHERE redu_Student_Ledger__c = :ledger.Id
        ];
        
        System.assert(before.isEmpty());
        System.debug(after.size());
        for (redu_Ledger_Entry__c le : after) {
            System.debug(le);
        }
        System.assert(after.size() == 1);            
        
        System.assertEquals(after.get(0).redu_Payment_Amount__c, payment.rio_ed__Payment_Amount__c);
        System.assertEquals(after.get(0).redu_Date__c, payment.rio_ed__Payment_Date__c);
        System.assertEquals(after.get(0).redu_Related_Payment__c, payment.Id);
        System.assertEquals(after.get(0).redu_Type__c, payment.rio_ed__Transaction_Type__c);
    }
    
    @isTest
    static void testUpdatePayment() {
        // first retrieve default EDA trigger handlers
       	List<hed.TDTM_Global_API.TdtmToken> tokens = hed.TDTM_Global_API.getTdtmConfig();

       	// Create our trigger handler using the constructor
       	// tokens.add(new hed.TDTM_Global_API.TdtmToken('redu_SFEE_StudentLedger_TDTM', 'rio_ed__Student_Fee__c', 'AfterInsert', 1.00));
        // tokens.add(new hed.TDTM_Global_API.TdtmToken('redu_PAYMENT_LedgerEntry_TDTM', 'rio_ed__Fee_Payment__c', 'AfterInsert;AfterUpdate;BeforeDelete', 1.00));

       	// Pass trigger handler config to set method for this test run
       	hed.TDTM_Global_API.setTdtmConfig(tokens);

        // Create our trigger handler
        redu_SFEE_StudentLedger_TDTM.installTDTMSetting();
        redu_PAYMENT_LedgerEntry_TDTM.installTDTMSetting();
       
       	// setup our test data...
        Contact ct = new Contact(LastName='Test');
       	insert ct;
       	hed__Program_Enrollment__c pe = new hed__Program_Enrollment__c(hed__Contact__c=ct.Id);
       	insert pe;
        rio_ed__Student_Fee__c sf = new rio_ed__Student_Fee__c(rio_ed__Program_Enrollment__c=pe.Id);
       	insert sf;
        rio_ed__Fee_Payment__c paymentToInsert = new rio_ed__Fee_Payment__c(rio_ed__Student_Fee__c = sf.Id, rio_ed__Payment_Amount__c = 500,
                                                                        rio_ed__Payment_Date__c = Date.today(), rio_ed__Transaction_Type__c = 'Refund');
        
        insert paymentToInsert;
        
        redu_Student_Ledger__c ledger = [
            SELECT Id 
            FROM redu_Student_Ledger__c 
            WHERE redu_Contact__c = :ct.Id
        ];
        List<redu_Ledger_Entry__c> before = [
            SELECT Id 
            FROM redu_Ledger_Entry__c 
            WHERE redu_Student_Ledger__c = :ledger.Id
        ];
                
        test.startTest();
       	// do some operations...
       	rio_ed__Fee_Payment__c paymentToUpdate = [
            SELECT rio_ed__Payment_Amount__c, rio_ed__Payment_Date__c 
            FROM rio_ed__Fee_Payment__c 
            WHERE Id = :paymentToInsert.Id
        ];
        
        paymentToUpdate.rio_ed__Payment_Amount__c = 1000;
        paymentToUpdate.rio_ed__Payment_Date__c = Date.today() - 7;
        paymentToUpdate.rio_ed__Transaction_Type__c = 'Payment';
        
        update paymentToUpdate;
        
        test.stopTest();
       	// validate our results...
       	List<redu_Ledger_Entry__c> after = [
            SELECT redu_Payment_Amount__c, redu_Date__c, redu_Related_Payment__c, redu_Type__c 
            FROM redu_Ledger_Entry__c 
            WHERE redu_Student_Ledger__c = :ledger.Id
        ];
        
        System.assertEquals(before.size(), after.size());
        
        rio_ed__Fee_Payment__c payment = [
            SELECT rio_ed__Payment_Amount__c, rio_ed__Payment_Date__c, rio_ed__Transaction_Type__c 
            FROM rio_ed__Fee_Payment__c
            WHERE Id = :paymentToInsert.Id
        ];
        
        System.assertEquals(after.get(0).redu_Payment_Amount__c, payment.rio_ed__Payment_Amount__c);
        System.assertEquals(after.get(0).redu_Date__c, payment.rio_ed__Payment_Date__c);
        System.assertEquals(after.get(0).redu_Related_Payment__c, payment.Id);
        System.assertEquals(after.get(0).redu_Type__c, payment.rio_ed__Transaction_Type__c);
    }
    
    @isTest
    static void testDeletePayment() {
        // first retrieve default EDA trigger handlers
       	List<hed.TDTM_Global_API.TdtmToken> tokens = hed.TDTM_Global_API.getTdtmConfig();

       	// Create our trigger handler using the constructor
       	// tokens.add(new hed.TDTM_Global_API.TdtmToken('redu_SFEE_StudentLedger_TDTM', 'rio_ed__Student_Fee__c', 'AfterInsert', 1.00));
       	// tokens.add(new hed.TDTM_Global_API.TdtmToken('redu_PAYMENT_LedgerEntry_TDTM', 'rio_ed__Fee_Payment__c', 'AfterInsert;AfterUpdate;BeforeDelete', 1.00));

       	// Pass trigger handler config to set method for this test run
       	hed.TDTM_Global_API.setTdtmConfig(tokens);

        // Create our trigger handler
        redu_SFEE_StudentLedger_TDTM.installTDTMSetting();
        redu_PAYMENT_LedgerEntry_TDTM.installTDTMSetting();
       
       	// setup our test data...
        Contact ct = new Contact(LastName='Test');
       	insert ct;
       	hed__Program_Enrollment__c pe = new hed__Program_Enrollment__c(hed__Contact__c=ct.Id);
       	insert pe;
        rio_ed__Student_Fee__c sf = new rio_ed__Student_Fee__c(rio_ed__Program_Enrollment__c=pe.Id);
       	insert sf;
        rio_ed__Fee_Payment__c paymentToInsert = new rio_ed__Fee_Payment__c(
            rio_ed__Student_Fee__c = sf.Id, 
            rio_ed__Payment_Amount__c = 500,
            rio_ed__Payment_Date__c = Date.today()
        );
        
        insert paymentToInsert;
        
        redu_Student_Ledger__c ledger = [
            SELECT Id 
            FROM redu_Student_Ledger__c 
            WHERE redu_Contact__c = :ct.Id
        ];
        List<redu_Ledger_Entry__c> before = [
            SELECT Id 
            FROM redu_Ledger_Entry__c 
            WHERE redu_Student_Ledger__c = :ledger.Id
        ];
        
        test.startTest();
       	// do some operations...
        rio_ed__Fee_Payment__c paymentToDelete = [
            SELECT Id 
            FROM rio_ed__Fee_Payment__c 
            WHERE Id = :paymentToInsert.Id
        ];
        delete paymentToDelete;
        
        test.stopTest();
       	// validate our results...
       	List<redu_Ledger_Entry__c> after = [
            SELECT Id 
            FROM redu_Ledger_Entry__c 
            WHERE redu_Student_Ledger__c = :ledger.Id
        ];
        
        System.assert(before.size() == 1);
        System.assert(after.isEmpty());
    }
}